# Mapeamento curado do índice por fase.
# Cada item: (padrao, descricao). O padrao e uma substring unica do caminho
# (comparacao NFC, sensivel a maiusculas). Grupos: N = Normas,
# M = Modelos, roteiros e checklists, D = Manuais e doutrina,
# J = Jurisprudencia e pareceres.

GRUPOS = {
    "N": "Normas",
    "M": "Modelos, roteiros e checklists",
    "D": "Manuais, guias e doutrina",
    "J": "Jurisprudência, pareceres e orientações",
}

SECOES = [
    {
        "id": "0", "titulo": "Base legal comum (consulta em todas as fases)",
        "artigos": "Lei 14.133/2021 (íntegra); LINDB e Lei 9.784/1999 subsidiariamente",
        "itens": {
            "N": [
                ("Federal - Lei 14133.2021.md", "Lei 14.133/2021 — Lei de Licitações e Contratos (texto compilado)"),
                ("Federal -  CF - 88.md", "Constituição Federal — art. 37, XXI (licitação) e art. 22, XXVII"),
                ("Lei Complementar 123 - ME e EPP", "LC 123/2006 — tratamento diferenciado a ME/EPP (arts. 42-49)"),
                ("Federal - Lei 9784 - Processo Administrativo", "Lei 9.784/1999 — processo administrativo federal (prazos, motivação)"),
                ("Lei Estadual 6782.2016 - Regula o Processo Administrativo no", "Lei Estadual 6.782/2016 — processo administrativo no Piauí"),
                ("Decreto Federal 12807.2025", "Decreto 12.807/2025 — valores da Lei 14.133 atualizados para 2026"),
                ("Decreto Federal 12343.2024", "Decreto 12.343/2024 — valores atualizados para 2025 (histórico)"),
                ("n21.872072023", "Decreto Estadual 21.872/2023 — regulamenta a Lei 14.133 no Poder Executivo do Piauí"),
                ("Ato PGJ 1382.2024 - Regulamenta", "Ato PGJ 1.382/2024 — regulamenta a Lei 14.133 no MPPI (norma-mãe)"),
                ("Ato PGJ 1413.2024", "Ato PGJ 1.413/2024 — altera o Ato 1.382/2024"),
                ("Ato PGJ 1538.2025", "Ato PGJ 1.538/2025 — altera atos normativos de contratação do MPPI"),
                ("Provimento TJPI nº 13.2025", "Provimento TJPI 13/2025 — regulamento de contratações do TJPI (referência comparada)"),
                ("lista-de-atos-normativos-e-estagios", "Lista federal de atos normativos e estágio de regulamentação da Lei 14.133"),
                ("Zênite - Compilado de Leis", "Zênite — compilado de leis sobre licitações e contratos"),
            ],
            "M": [
                ("Fluxogramas_Atualizados", "TJPI — fluxogramas das etapas da contratação (preparatória, seleção, execução)"),
                ("instrumento-de-padronizacao-dos-procedimentos", "AGU/MGI — Instrumento de Padronização dos Procedimentos de Contratação (OCR com falhas)"),
            ],
            "D": [
                ("Licitacoes e Contratos - Orientacoes e Jurisprudencia do TCU - 5a Edicao", "TCU — Licitações e Contratos: Orientações e Jurisprudência, 5ª ed."),
                ("Manual Institucional - Compras e Licitacoes - TRT 2a Regiao 2025-2027", "TRT-2 — Manual institucional de compras e licitações 2025-2027"),
                ("Manual de Licitacoes e Contratos TJPI (2023-2024)", "TJPI — Manual de licitações e contratos 2023-2024"),
                ("Biblioteca_Manuais_e_Cursos/Licitações e contratos.md", "TCE-SP — Licitações e contratos (manual básico)"),
                ("Perguntas e Respostas- Licitações e Contratações", "Perguntas e respostas sobre licitações e contratações"),
                ("TCE-SC – Perguntas e respostas", "TCE-SC — Perguntas e respostas: licitações e contratos (2025)"),
                ("Referencial_Licitacoes_Contratos_TCESC", "TCE-SC — Referencial de licitações e contratos"),
                ("Aspectos gerais da nova lei", "Apostila — aspectos gerais da Lei 14.133 (Jamil Manasfi)"),
                ("Livro - NLLC Esquematizada", "Livro — NLLC esquematizada"),
                ("Quadro_Comparativo_Nova_Lei", "Quadro comparativo Lei 14.133 x Lei 8.666"),
            ],
            "J": [
                ("Estudo_Tematico_Agosto_2025", "TCE-MG — estudo temático de consultas sobre a Lei 14.133 (ago/2025)"),
                ("2º Simpósio de Licitações", "CJF — enunciados do 2º Simpósio de Licitações e Contratos da Justiça Federal"),
                ("cgu_ementarioaquisicoes", "CGU — ementário de aquisições 2026"),
                ("PARECER Nº 00060-2024-DECOR", "Parecer AGU 00060/2024/DECOR"),
                ("Parecer1774358321", "Parecer AGU (CONUNI) — uniformização de entendimento"),
            ],
        },
        "transicao": [
            ("n20.110132021", "Decreto Estadual 20.110/2021 — transição 8.666 → 14.133"),
            ("n21.910172023", "Decreto Estadual 21.910/2023 — transição de regime"),
            ("n21.980132023", "Decreto Estadual 21.980/2023 — transição de regime"),
            ("n22.652272023", "Decreto Estadual 22.652/2023 — transição de regime"),
        ],
        "lacunas": [],
    },
    {
        "id": "1", "titulo": "Governança, PCA e agentes públicos",
        "artigos": "Lei 14.133, art. 11, parágrafo único; art. 12, VII; art. 169 (linhas de defesa); arts. 7º-8º (agentes)",
        "itens": {
            "N": [
                ("Resolucao-CNMP-n-281", "Resolução CNMP 281/2023 — política de governança das contratações no MP"),
                ("Resolução TCE-PI 039.2023", "Resolução TCE-PI 39/2023 — Plano de Contratações Anual"),
                ("Ato PGJMPPI - n1381.0", "Ato PGJ 1.381/2024 — PCA no MPPI"),
                ("Ato PGJMPPI - n1414.0", "Ato PGJ 1.414/2024 — agentes de contratação, equipe de apoio e comissão"),
                ("Ato PGJMPPI - n1448.0", "Ato PGJ 1.448/2024 — agentes públicos da contratação"),
                ("Ato PGJ 0479.2014", "Ato PGJ 479/2014 — estrutura e atribuições das unidades administrativas do MPPI (alterado pelos Atos 1.106/2021, 1.180/2022 e 1.480/2025)"),
                ("Portaria PGJ 5644.2025", "Portaria PGJ 5.644/2025 — designação de agentes de contratação e pregoeiros"),
                ("Portaria PGJ 4337.2024", "Portaria PGJ 4.337/2024 — agente de contratação e pregoeiro"),
                ("Portaria PGJ 1318.2026", "Portaria PGJ 1.318/2026 — equipe de planejamento (art. 18)"),
                ("PORTARIA_PGJPI_NA___2067.2026", "Portaria PGJ 2.067/2026 — equipe de planejamento (art. 18)"),
                ("Portaria PGJ 1040.2025", "Portaria PGJ 1.040/2025 — equipe de planejamento"),
                ("Portaria PGJ 3315.2025", "Portaria PGJ 3.315/2025 — equipe de planejamento da contratação"),
                ("Portaria PGJMPPI - n870.0", "Portaria PGJ 870/2025 — designações da área de contratações"),
                ("Portaria PGJMPPI - n942.0", "Portaria PGJ 942/2025 — designações da área de contratações"),
                ("Portaria PGJMPPI - n3448.0", "Portaria PGJ 3.448/2024 — designações da área de contratações"),
                ("Portaria PGJMPPI - n4333.0", "Portaria PGJ 4.333/2024 — designações da área de contratações"),
            ],
            "M": [
                ("03_MPPI/PCA 2025.md", "PCA 2025 do MPPI"),
                ("PCA 2026/PCA 2026 - Plano de Contratacoes Anual Versao 3.0", "PCA 2026 do MPPI — versão 3.0"),
                ("Relação de Demandas Suspensas", "PCA 2026 — relação de demandas suspensas e retidas (184 registros)"),
                ("PEI_2022_2029", "Planejamento Estratégico Institucional do MPPI 2022-2029"),
                ("Relatorio_PCA_2027", "Relatório do PCA 2027"),
                ("Tutorial_PCA_MPPI_2027", "Tutorial do PCA MPPI 2027 (cabeçalho ainda cita 2026)"),
                ("Roteiro_Video_PCA_MPPI", "Roteiro de vídeo explicativo do PCA MPPI"),
                ("Guia Onboarding", "Guia de onboarding do sistema PCA-MPPI"),
            ],
            "D": [
                ("PORTARIA SEGES_ME Nº 8.678", "Portaria SEGES/ME 8.678/2021 — governança das contratações (texto integral)"),
                ("Enap - Caderno de curso Nova lei de licitações - Planejamento e Governança", "Enap — caderno de curso: planejamento e governança"),
                ("PassoapassoPGC", "Passo a passo do PGC (Planejamento e Gerenciamento de Contratações)"),
                ("Manual-de-Mapeamento-e-Melhoria-de-Processos-do-MPPI", "MPPI — manual de mapeamento e melhoria de processos"),
                ("Tutorial compras executivo", "Compras.gov.br — tutorial Compras Executivo (jan/2026)"),
            ],
            "J": [
                ("Acordao TCU 2037.2019", "Acórdão TCU 2.037/2019-Plenário — governança das contratações"),
            ],
        },
        "lacunas": ["Não há norma do MPPI sobre plano de logística sustentável nem sobre política de gestão de estoques."],
    },
    {
        "id": "2", "titulo": "Formalização da demanda (DFD)",
        "artigos": "Lei 14.133, art. 18, caput; art. 12, VII (alinhamento ao PCA)",
        "itens": {
            "N": [],
            "M": [
                ("03_MPPI/Modelo de DFD.md", "Modelo de DFD do MPPI"),
                ("Modelo de DFD - TIC", "Modelo de DFD do MPPI para TIC"),
                ("DOD - Documento de Oficializacao da Demanda MPPE", "MPPE — Documento de Oficialização da Demanda, v3.0"),
                ("Prompt Revisor - DFD", "Prompt revisor de DFD (IA)"),
                ("Checklist de Auditoria - DFD", "Checklist de auditoria do DFD"),
            ],
            "D": [], "J": [],
        },
        "lacunas": [],
    },
    {
        "id": "3", "titulo": "Estudo Técnico Preliminar (ETP)",
        "artigos": "Lei 14.133, art. 6º, XX; art. 18, I e §§ 1º-2º",
        "itens": {
            "N": [
                ("Federal - IN 58.2022", "IN SEGES 58/2022 — ETP no sistema ETP Digital"),
                ("Resolução TCE-PI 041.2023", "Resolução TCE-PI 41/2023 — ETP e TR (compilada com a Res. 2/2026)"),
                ("Resolução TCE-PI 002.2026", "Resolução TCE-PI 2/2026 — altera a Res. 41/2023"),
            ],
            "M": [
                ("ETP - Estudo Tecnico Preliminar MPPE", "MPPE — modelo de ETP, v5.0"),
                ("Prompt Revisor - ETP", "Prompt revisor de ETP (IA)"),
                ("Checklist de Auditoria - ETP", "Checklist de auditoria do ETP"),
                ("E-BOX 01", "E-BOX 01 — ETP para aquisições e serviços em geral"),
                ("E-BOX 02", "E-BOX 02 — ETP para obras e serviços de engenharia"),
                ("E-BOX 03", "E-BOX 03 — ETP para TIC"),
            ],
            "D": [
                ("Publicação - ETP - UFJF", "UFJF — publicação sobre ETP"),
                ("TCC - ETP - O Dilema", "TCC — ETP: o dilema entre necessidade e solução"),
                ("Planejamento_ fundamento legal par", "Zênite — como descrever a necessidade no planejamento"),
                ("TCE-PR – Cartilha de Obras", "TCE-PR — cartilha de ETP para obras e serviços de engenharia"),
                ("Manual de Planejamento da Contratação-SEMA_PMT-2023", "PMT/SEMA — manual de planejamento da contratação (2023)"),
                ("Apostila_Capacitacao_Contratacoes_Modulo_01", "Apostila de capacitação em contratações — módulo 01"),
                ("Livro - ELABORAÇÃO DE ETP E TR", "Livro — elaboração de ETP e TR com ChatGPT"),
            ],
            "J": [],
        },
        "lacunas": [],
    },
    {
        "id": "4", "titulo": "Gestão de riscos",
        "artigos": "Lei 14.133, art. 18, X; art. 22 (matriz de riscos); art. 6º, XXVII",
        "itens": {
            "N": [
                ("Ato PGJ 1480.2025 - Retira CONINT", "Ato PGJ 1.480/2025 — três linhas de defesa; Controladoria Interna antes da homologação e listas de verificação"),
                ("Ato PGJ 1106.2021", "Ato PGJ 1.106/2021 — fluxo da Controladoria Interna (art. 59, XI, do Ato 479/2014; alterado pelo 1.480/2025)"),
                ("SEAD Portaria 631.2025", "Portaria SEAD 631/2025 — política de gestão de riscos (Executivo PI)"),
            ],
            "M": [
                ("Anexo_1204260_MAPA_DE_RISCOS", "MPPI — mapa de riscos de licitações e contratos"),
                ("Matriz de Riscos MPPE", "MPPE — matriz de riscos, v2.0"),
                ("Tutorial de como criar matriz de riscos", "Compras.gov.br — tutorial para criar matriz de riscos"),
            ],
            "D": [
                ("Palestra - Inventário de Riscos", "Palestra — inventário de riscos e controles nas contratações"),
            ],
            "J": [
                ("PARECER n. 00006-2025-GAB-DECOR", "Parecer AGU 00006/2025/GAB/DECOR"),
            ],
        },
        "lacunas": ["Não há manual de gestão de riscos do MPPI nem do Estado; só a Portaria SEAD e o Ato 1.480."],
    },
    {
        "id": "5", "titulo": "Pesquisa de preços e estimativa da despesa",
        "artigos": "Lei 14.133, art. 23; art. 18, IV",
        "itens": {
            "N": [
                ("Federal - IN 65.2021", "IN SEGES 65/2021 — pesquisa de preços (bens e serviços)"),
                ("Federal - IN 91.2022", "IN SEGES 91/2022 — pesquisa de preços para obras e serviços de engenharia"),
                ("CGE IN 01.2021", "IN CGE-PI 01/2021 — pesquisa de preços no Executivo estadual"),
                ("Resolução TCE-PI 017.2024", "Resolução TCE-PI 17/2024 — pesquisa de preços"),
            ],
            "M": [
                ("Banco de Precos - Passo a Passo Cotacao Nova e Rapida Plus", "Banco de Preços — cotação nova e rápida (Plus)"),
                ("Manual - BPPlus", "Banco de Preços — manual BP Plus"),
                ("Como Convidar Fornecedores", "Banco de Preços — convidar fornecedores, log e TR"),
                ("Cotação Nova e Rápida (+lotes)", "Banco de Preços — cotação nova e rápida com lotes (Plus)"),
                ("Cotação Nova e Rápida (Standard)", "Banco de Preços — cotação nova e rápida (Standard)"),
                ("copiar e compartilhar cotações", "Compras.gov.br — copiar e compartilhar cotações no Pesquisa de Preço"),
            ],
            "D": [
                ("Curso Banco de Preços - Pesquisa de Preços", "Curso Banco de Preços — pesquisa de preços"),
                ("Caderno de Logistica - Pesquisa de Preços - 2017", "Caderno de Logística — pesquisa de preços (2017)"),
                ("Pesquisa de Preços Nas contratações Publicas 3", "Pesquisa de preços nas contratações públicas"),
                ("Pesquisa de Preços nas Contratações Públicas - Parte 01", "Curso — TR e pesquisa de preços, parte 1"),
                ("Pesquisa de Preços nas Contratações Públicas - Parte 02", "Curso — TR e pesquisa de preços, parte 2"),
                ("Apresentação - Da Especificação do Objeto", "Apresentação — da especificação do objeto ao orçamento estimado"),
                ("Artigo - A Pesquisa de Preços Concomitante", "Artigo — pesquisa de preços concomitante à seleção na dispensa eletrônica"),
                ("Operacionalização do Sistema - Jamil", "Material de apoio — pesquisa de preços no Compras.gov.br (Jamil Manasfi)"),
                ("Guia referencial para identificação, quantificaçao", "CGU — guia para identificar, quantificar e mitigar superfaturamento"),
            ],
            "J": [
                ("TCE-SC - NOTA TÉCNICA Nº TC-19-2026", "TCE-SC — Nota Técnica TC-19/2026"),
            ],
        },
        "lacunas": ["Falta material atualizado: o Caderno de Logística é de 2017; não há o caderno de pesquisa de preços de 2024 nem o manual do STJ."],
    },
    {
        "id": "6", "titulo": "Termo de Referência e Projeto Básico",
        "artigos": "Lei 14.133, art. 6º, XXIII e XXV; art. 40; art. 47",
        "itens": {
            "N": [
                ("Federal - IN 81.2022 - TR.md", "IN SEGES 81/2022 — TR no sistema TR Digital"),
                ("Decreto Federal 10818", "Decreto 10.818/2021 — bens de consumo comuns e de luxo"),
            ],
            "M": [
                ("Pregão e Concorrência/Compras/modelo-de-termo-de-referencia-compras", "AGU — modelo de TR para compras (pregão/concorrência)"),
                ("modelo-de-termo-de-referencia-compras-tic", "AGU — modelo de TR para compras de TIC"),
                ("modelo-de-termo-de-referencia-servicos-tic", "AGU — modelo de TR para serviços de TIC"),
                ("termo-de-justificativas-tecnicas-relevantes-obras", "AGU — termo de justificativas técnicas relevantes (obras)"),
                ("TR - Termo de Referencia MPPE", "MPPE — modelo de TR, v3.0"),
                ("Prompt Revisor - TR.md", "Prompt revisor de TR (IA)"),
                ("Prompt Revisor - TR - Quesitos", "Prompt revisor de TR por quesitos/artigo (IA)"),
                ("Checklist Detalhado do TR", "Checklist detalhado do TR (rascunho)"),
                ("Checklist de Auditoria - Termo de Referencia", "Checklist de auditoria do TR"),
                ("Checklist de Auditoria - Revisao e Aprofundamento de Quesitos", "Checklist de auditoria — aprofundamento de quesitos do TR"),
            ],
            "D": [], "J": [],
        },
        "lacunas": [],
    },
    {
        "id": "7", "titulo": "Revisão do planejamento e análise jurídica",
        "artigos": "Lei 14.133, art. 53 (controle prévio de legalidade); art. 72, III",
        "itens": {
            "N": [
                ("Ato PGJ 1383.2024", "Ato PGJ 1.383/2024 — dispensa de parecer jurídico (art. 75, I e II, e art. 53, § 5º)"),
                ("Ato PGJMPPI - n1415.0", "Ato PGJ 1.415/2024 — análise jurídica das contratações"),
                ("Ato PGJ 1180.2022", "Ato PGJ 1.180/2022 — assessoria para pareceres em processos licitatórios"),
                ("Ato PGJMPPI - n1456.0", "Ato PGJ 1.456/2024 — Manifestações Jurídicas Referenciais (MJR)"),
            ],
            "M": [
                ("TAPP DIMPLANC - Modelo Analise Preliminar", "Modelo de TAPP — termo de análise preliminar do planejamento"),
                ("TAAP - TERMO", "Modelo de TAAP — termo de análise preliminar do planejamento"),
                ("TAPPC ASSGERLICT - Checklist", "Modelo de TAPPC — checklist da ASSGERLICT (revisado pela assessoria jurídica, 2025)"),
                ("TAPP_DIMPLANC_000_202X", "Modelo de documento TAPP (estrutura)"),
                ("TAPP-D - Diagnostico", "TAPP-D — diagnóstico e matriz de notas"),
                ("TAPP-D - Nota Tecnica de Revisao", "TAPP-D — nota técnica de revisão da minuta"),
                ("TAPP_D_Minuta_Revisada_v4", "TAPP-D — minuta revisada v4"),
                ("TAPP DIMPLANC 006_2024-0", "TAPP 006/2024 — exemplo (lavagem a seco de togas)"),
                ("TAPP DIMPLANC 004_2025-0", "MPPE — TAPP 004/2025-0 (empresa gráfica)"),
                ("TAPP DIMPLANC 004_2025-1", "MPPE — TAPP 004/2025-1 (empresa gráfica)"),
                ("Oficio_Devolucao_Saneamento_ETP_TR", "Ofício de devolução para saneamento de ETP/TR"),
                ("Aprovacao_de_Artefatos_14133_SEI_1422714", "Modelo SEI — aprovação de artefatos"),
                ("SEI_1496852_Aprovacao_Artefatos", "Modelo SEI — aprovação de artefatos (2º modelo)"),
                ("Checklist padronizado - Fase de planejamento", "MPPE — checklist da fase de planejamento, v2.0"),
                ("Checklist de Auditoria - Fase Interna", "Checklist de auditoria — fase interna e seleção do fornecedor"),
                ("Lista de Verificacao - Fase Interna de Selecao", "Lista de verificação — fase interna"),
                ("Nota_Tecnica_Sugestoes_Redacao", "Nota técnica — sugestões de redação e correção de artefatos"),
                ("Caderno_Prompts_IA_Auditoria", "Caderno de prompts de IA para auditoria de licitações"),
                ("SEI_TJPI - 7097234", "TJPI — análise de primeira linha da SLC"),
                ("SEI_TJPI - 7123034", "TJPI — lista de verificação SGC"),
                ("SEI_TJPI - 7134934", "TJPI — lista de verificação SLC"),
                ("Lista de Verificacao SGC TJPI", "TJPI — lista de verificação SGC (conformidade licitatória)"),
                ("Compras/modelo-de-lista-de-verificacao-compras-e-servicos-sem-mao", "AGU — lista de verificação: compras e serviços sem DEMO"),
                ("Serviços com Demo/modelo-de-lista-de-verificacao", "AGU — lista de verificação: serviços com DEMO"),
                ("modelo-de-lista-de-verificacao-obras", "AGU — lista de verificação: obras e serviços de engenharia"),
                ("modelo-de-lista-de-verificacao-tic", "AGU — lista de verificação: TIC"),
            ],
            "D": [],
            "J": [
                ("PARECER n. 00003-2025-GAB-CGU", "Parecer AGU 00003/2025/GAB/CGU"),
                ("PARECER n. 00196-2024-E-CJU", "Parecer AGU 00196/2024/E-CJU/SCOM"),
                ("SEI_TJPI - 7071569", "TJPI — justificativa (parecer do agente)"),
            ],
        },
        "lacunas": [],
    },
    {
        "id": "8", "titulo": "Fase externa: edital, publicidade e sessão",
        "artigos": "Lei 14.133, art. 17 (fases); art. 25 (edital); arts. 28-32 (modalidades); arts. 54-58",
        "itens": {
            "N": [
                ("Lei Estadual 7482.2021", "Lei Estadual 7.482/2021 — pregão eletrônico e dispensa eletrônica no Piauí"),
                ("Decreto Estadual 23.865.2025", "Decreto Estadual 23.865/2025 — unificação da plataforma de compras públicas do Piauí"),
                ("Portaria Estadual - n..0342021", "Portaria estadual 034/2021 — procedimentos de licitação"),
                ("n11.346302004", "Decreto Estadual 11.346/2004 — pregão (regime anterior)"),
            ],
            "M": [
                ("modelo-de-edital-pregao-e-concorrencia-menor-preco", "AGU — edital de pregão/concorrência (menor preço ou maior desconto)"),
                ("modelo-de-edital-concorrencia-tecnica-e-preco", "AGU — edital de concorrência (técnica e preço)"),
                ("modelo-de-edital-pregao-e-concorrencia-tic", "AGU — edital de pregão/concorrência para TIC"),
                ("Modelo Proposta de Precos", "MPPI — modelo de proposta de preços"),
                ("Folha de Rosto - Edital Pregao", "MPPI — folha de rosto do edital de pregão eletrônico (ASSGERLICT, 2025)"),
                ("Roteiro_Falas_Sessao_Publica", "Roteiro de falas da sessão pública do pregão eletrônico"),
                ("Glossario de Mensagens", "Glossário de mensagens da sessão pública do pregão"),
                ("CARTILHA-DE-MENSAGENS-PADRONIZADAS", "SEAD-PI — cartilha de mensagens padronizadas para o agente de contratação"),
                ("01-Lei-14133-Lista-de-Verificacao-Pregao-Eletronico-SEM-SRP", "PGE-PI — lista de verificação: pregão eletrônico sem SRP (out/2025)"),
                ("Lei-14133-Lista-de-Verificacao-Pregao-Eletronico-SEM-SRP-Servicos-Comuns", "PGE-PI — lista de verificação: pregão sem SRP, serviços comuns de engenharia"),
                ("Lei-14133-Lista-de-Verificacao-Concorrencia-Eletronica-SEM-SRP", "PGE-PI — lista de verificação: concorrência sem SRP, obras e serviços especiais"),
            ],
            "D": [
                ("Manual completo - Manual Compras.gov.br - Pregão", "Compras.gov.br — manual completo do pregão eletrônico"),
                ("Tutorial Compras.gov.br - Operacionalizacao de Contratacoes Presenciais", "Compras.gov.br — operacionalização de contratações presenciais"),
                ("critério de julgamento, melhor técnica", "Compras.gov.br — critério melhor técnica ou conteúdo artístico"),
                ("Novo divulgação de contratações - Evento de alteração", "Compras.gov.br — evento de alteração na divulgação"),
                ("Manual de Orientacao - Compras Publicas Baseadas na Relacao", "Manual — julgamento por maior retorno econômico e custo do ciclo de vida"),
                ("Manual de Compras Baseadas na Relação Custo", "Manual de compras baseadas na relação custo-benefício (abr/2025)"),
            ],
            "J": [
                ("impacto do uso do orçamento sigiloso", "CGU — avaliação do orçamento sigiloso e dos modos de disputa"),
            ],
        },
        "lacunas": [],
    },
    {
        "id": "9", "titulo": "Julgamento das propostas e habilitação",
        "artigos": "Lei 14.133, arts. 59-61 (julgamento); arts. 62-70 (habilitação)",
        "itens": {
            "N": [
                ("Decreto Estadual 22811.2024", "Decreto Estadual 22.811/2024 — regularidade fiscal, econômico-financeira e administrativa"),
                ("Decreto Estadual 24144.2025", "Decreto Estadual 24.144/2025 — equidade de gênero como critério de desempate"),
                ("n16.21252015", "Decreto Estadual 16.212/2015 — tratamento a ME/EPP"),
                ("Decreto Estadual 11320.2004", "Decreto Estadual 11.320/2004 — Cadastro Único de Fornecedores (CUF)"),
            ],
            "M": [
                ("Check List Habilitação", "MPPI — checklist de habilitação"),
            ],
            "D": [
                ("Zênite - Apresentação - Curso Habilitação", "Zênite — curso de habilitação nas contratações"),
            ],
            "J": [
                ("PARECER Nº 00002-2025-CNLCA", "Parecer AGU 00002/2025/CNLCA"),
                ("PARECER Nº 00017-2024-CNLCA", "Parecer AGU 00017/2024/CNLCA"),
                ("PARECER Nº 00019-2024-CNLCA", "Parecer AGU 00019/2024/CNLCA"),
                ("PARECER n. 00006-2025CNLCA", "Parecer AGU 00006/2025/CNLCA"),
                ("estudo_tematico_recuperacao_judicial", "Estudo temático — empresas em recuperação judicial"),
            ],
        },
        "lacunas": [],
    },
    {
        "id": "10", "titulo": "Recursos, adjudicação e homologação",
        "artigos": "Lei 14.133, arts. 164-168 (impugnações e recursos); art. 71",
        "itens": {
            "N": [],
            "M": [],
            "D": [
                ("Artigo - A fase recursal", "Artigo — a fase recursal na Lei 14.133 (comparativo com 8.666, 10.520 e 12.462)"),
                ("Artigo - Das Impugnações", "Artigo — impugnações, esclarecimentos e recursos nas dispensas"),
                ("eventos de anulação, suspensão e revogação", "Compras.gov.br — eventos de anulação, suspensão e revogação"),
            ],
            "J": [],
        },
        "lacunas": [
            "Fase mais fraca da base: só dois artigos e um tutorial.",
            "Falta modelo do MPPI de decisão de recurso e de termo de homologação.",
        ],
    },
    {
        "id": "11", "titulo": "Contratação direta (dispensa e inexigibilidade)",
        "artigos": "Lei 14.133, arts. 72-75",
        "itens": {
            "N": [
                ("Federal - IN 67.2021", "IN SEGES 67/2021 — dispensa eletrônica"),
                ("Portaria_n_2899_2023", "TJPI — Portaria 2.899/2023 (dispensa de licitação)"),
            ],
            "M": [
                ("POP - Contratacao Direta Art 75 IX", "MPPI — POP art. 75, IX (empresa pública)"),
                ("Inexigibilidade Art 74 I - ", "MPPI — POP inexigibilidade art. 74, I (exclusividade)"),
                ("Inexigibilidade Art 74 II - ", "MPPI — POP inexigibilidade art. 74, II (setor artístico)"),
                ("Inexigibilidade Art 74 III", "MPPI — POP inexigibilidade art. 74, III (cursos e palestras)"),
                ("POP - Contratacao por Dispensa Eletronica", "MPPI — POP dispensa eletrônica"),
                ("POP-CLC-02", "MPPI — POP dispensa de licitação (POP-CLC-02)"),
                ("Roteiro - Dispensa (lista de documentos 2024)", "MPPI — roteiro de dispensa (lista de documentos 2024)"),
                ("Roteiro - Dispensa Eletronica", "MPPI — roteiro de dispensa eletrônica"),
                ("Roteiro - Dispensa sem Disputa", "MPPI — roteiro de dispensa sem disputa"),
                ("Roteiro - Inexigibilidade", "MPPI — roteiro de inexigibilidade"),
                ("Modelo - Termo de Justificativa de Dispensa sem Disputa", "Modelo de termo de justificativa de dispensa sem disputa"),
                ("Prompts - Contratacao Direta", "Prompts para contratação direta (art. 72)"),
                ("Checklist de Auditoria - Contratacoes Diretas", "Checklist de auditoria — dispensas e inexigibilidades"),
                ("modelo-de-aviso-de-contratacao-direta", "AGU — aviso de contratação direta"),
                ("modelo-de-lista-de-verificacao-contratacoes-diretas", "AGU — lista de verificação: contratações diretas"),
                ("Contratação Direta/modelo-de-termo-de-referencia-compras", "AGU — TR para compras (contratação direta)"),
                ("Contratação Direta/modelo-de-termo-de-referencia-servicos-e-obras-lei-no-14-133-mai-26", "AGU — TR para serviços e obras (contratação direta, mai/2026)"),
                ("TJ_MA_termo_de_referencia_dispensa", "TJMA — TR de dispensa por item (2024)"),
                ("TJMA - checklist_dispensa_eletronica", "TJMA — checklist de dispensa eletrônica"),
                ("SEI_TJPI - 7176291", "TJPI — aviso de dispensa de licitação"),
            ],
            "D": [
                ("dispensas com disputa no Novo DC", "Compras.gov.br — publicar dispensas com disputa"),
                ("dispensas sem disputa e inexibilidades", "Compras.gov.br — publicar dispensas sem disputa e inexigibilidades"),
                ("Manual Operacional - Dispensa Eletronica no Compras.gov.br", "Compras.gov.br — manual operacional da dispensa eletrônica"),
                ("Manual MPBA - Cadastro no Compras.gov", "MPBA — cadastro de dispensas e inexigibilidades no Compras.gov"),
                ("Apresentação - Contratação Direta - GOVSP", "Governo de SP — apresentação sobre contratação direta"),
                ("Apostila - CURSO DE CONTRATAÇÃO DIRETA", "Apostila — contratação direta e dispensa eletrônica com IA (Jamil)"),
                ("Artigo - As Quatro Formatações", "Artigo — as quatro formatações da dispensa por valor"),
                ("Artigo - Leonardo Mota", "Artigo — dispensa de licitação na Lei 14.133 (Leonardo Mota)"),
                ("Artigo - Sem Singularidade", "Artigo — sem singularidade não há inexigibilidade"),
                ("Artigo - A existência de prop inferiores", "Artigo — propostas inferiores e inexigibilidade de notório especialista"),
                ("Zênite - É possível que a Administração dispense", "Zênite — dispensa da divulgação do aviso na dispensa por valor"),
                ("Zênite Fácil - Dispensa Eletrônica", "Zênite Fácil — dispensa eletrônica"),
                ("Nota Técnica 5-2024", "Nota Técnica 5/2024 — dispensa eletrônica"),
                ("OrientaessobreasEvoluesdaCompraDireta", "Orientações sobre as evoluções da compra direta"),
                ("UNIFESPA - Fluxo Descritivo", "UNIFESPA — fluxo das contratações diretas para capacitação"),
                ("Decreto PMT 25530.2024", "Decreto Municipal (Teresina) 25.530/2024 — contratação direta"),
                ("Guia Prático de Contratações em Situações de Calamidade", "CGU — guia de contratações em calamidade pública (MP 1.221)"),
                ("Publicacao PGE-PI - Lista de Contratacoes de Pequeno Valor", "PGE-PI — publicação da lista de contratações de pequeno valor no DOE"),
            ],
            "J": [
                ("ON 88.2024 AGU", "ON AGU 88/2024 — dispensa em razão do valor"),
                ("ON 89.2024 AGU", "ON AGU 89/2024 — contratações diretas e alterações contratuais"),
                ("Parecer Referencial 00001.2026", "Parecer referencial 00001/2026 CONJUR-MS"),
                ("Parecer Referencial 00003.2025", "Parecer referencial 00003/2025 CONJUR-EB — inexigibilidade para cursos e pós-graduação"),
                ("Manifestação Jurídico Referencial - MJR - n92", "MPPI — MJR 92/2024 (dispensa, art. 75, I e II)"),
                ("MJR 92 - Aprovação MJR", "MJR 92 — aprovação"),
                ("MJR 92 - Analise Preliminar", "MJR 92 — análise preliminar de conformidade"),
                ("MJR 92 - Analise Conclusiva", "MJR 92 — análise conclusiva de conformidade"),
                ("PARECER Nº 4632024-PLCCAPGM", "Parecer PGM 463/2024 — dispensa de licitação"),
                ("PARECER Nº 00023-2025-CGAQ", "Parecer AGU 00023/2025/CGAQ"),
                ("PARECER n. 00860-2023", "Parecer AGU 00860/2023/E-CJU/SCOM"),
                ("PARECER n. 00019-2025-DECOR", "Parecer AGU 00019/2025/DECOR"),
            ],
        },
        "pge": [
            ("Lista de Verificação - Contratação Direta - Serviços ou Compras/Lei-14133-Lista-de-Verificacao-Contratacao-Direta-Servicos-ou-Compras.md", "PGE-PI — LV contratação direta: serviços ou compras"),
            ("Lista de Verificação - Contratação Direta - Obras/Lei-14133-Lista-de-Verificacao-Contratacao-Direta-Obras.md", "PGE-PI — LV contratação direta: obras"),
            ("Lei-14133-Lista-de-Verificacao-Direta-Pequeno-Valor-Servicos-e-Compras.md", "PGE-PI — LV pequeno valor: serviços e compras (75, II)"),
            ("Lei-14133-Lista-de-Verificacao-Contratacao-Direta-Pequeno-Valor-Obras.md", "PGE-PI — LV pequeno valor: obras (75, I)"),
            ("Lei-14133-Lista-de-Verificacao-Contratacao-Direta-Pequeno-Valor-Servicos-Comuns-de-Engenharia.md", "PGE-PI — LV pequeno valor: serviços comuns de engenharia"),
            ("LV - Contratação Direta - Serv Comuns Eng/Lista-de-Verificacao-Contratacao-Direta-Servicos-Comuns-de-Engenharia.md", "PGE-PI — LV contratação direta: serviços comuns de engenharia"),
        ],
        "lacunas": [],
    },
    {
        "id": "12", "titulo": "Procedimentos auxiliares e Sistema de Registro de Preços",
        "artigos": "Lei 14.133, arts. 78-88 (credenciamento, pré-qualificação, PMI, SRP, registro cadastral)",
        "itens": {
            "N": [
                ("Decreto Federal 11462", "Decreto 11.462/2023 — Sistema de Registro de Preços (federal)"),
                ("n21.938282023", "Decreto Estadual 21.938/2023 — SRP no Piauí (arts. 82-86)"),
                ("n22.023262023", "Decreto Estadual 22.023/2023 — SIGRP"),
                ("DECRETO - n11.319", "Decreto Estadual 11.319/2004 — SRP (regime anterior)"),
                ("SEAD IN 01.2021", "IN SEAD 01/2021 — limite de adesões às atas da SEADPREV"),
                ("Decreto Estadual 23868.2025", "Decreto Estadual 23.868/2025 — Procedimento de Manifestação de Interesse (PMI)"),
                ("n20.096112021", "Decreto Estadual 20.096/2021 — credenciamento para unidades de saúde"),
            ],
            "M": [
                ("POP - Contratacao por ARP Propria", "MPPI — POP contratação por ARP própria (POP-CLC-05)"),
                ("POP - Contratacao por Adesao a Ata", "MPPI — POP adesão a ARP (carona)"),
                ("POP - Prorrogacao de Vigencia de Ata", "MPPI — POP prorrogação de vigência de ARP"),
                ("Roteiro - Adesao a ARP no Compras.gov", "MPPI — roteiro de adesão a ARP no Compras.gov"),
                ("Roteiro - Contratacao por ARP", "MPPI — roteiro de contratação por ARP"),
                ("Roteiro - Liberacao de ARP para Adesao", "MPPI — roteiro de liberação de ARP para adesão"),
                ("Roteiro - Credenciamento", "MPPI — roteiro do credenciamento (art. 79), da demanda à gestão do rol de credenciados"),
                ("Modelo - Manifestacao do Ordenador de Despesas", "Modelo — manifestação do ordenador sobre liberação de adesão (Acórdão TCE-PI 394-A/2026)"),
                ("Modelo - Oficio ao Orgao Aderente", "Modelo — ofício ao órgão aderente"),
                ("Despacho_PGJ_Liberacao_Adesao", "Modelo SEI — despacho PGJ de liberação de adesão"),
                ("SEI_0978996_Ata_de_Registro_de_Precos", "Exemplo — ata de registro de preços (SEI 0978996)"),
                ("modelo-de-ata-de-registro-de-precos", "AGU — modelo de ata de registro de preços"),
                ("modelo-de-edital-credenciamento", "AGU — modelo de edital de credenciamento"),
                ("SIte_PGE_PI/Adesão/Lei-14133-Lista-de-Verificacao-Adesao.md", "PGE-PI — LV adesão a ARP"),
                ("Adesão ARP Gerenciada pela SEAD/Lei-14133-Lista-de-Verificacao-Adesao-SEAD.md", "PGE-PI — LV adesão a ARP gerenciada pela SEAD"),
                ("02-Lei-14133-Lista-de-Verificacao-Pregao-Eletronico-COM-SRP", "PGE-PI — LV pregão eletrônico com SRP (out/2025)"),
                ("Lei-14133-Lista-de-Verificacao-Pregao-Eletronico-COM-SRP-Servicos-Comuns", "PGE-PI — LV pregão com SRP, serviços comuns de engenharia"),
                ("Lei-14133-Lista-de-Verificacao-Concorrencia-Eletronica-COM-SRP", "PGE-PI — LV concorrência com SRP, obras e serviços especiais"),
            ],
            "D": [
                ("Artigo - Como formalizar a prorrogação", "Artigo — como formalizar a prorrogação de vigência de ARP"),
                ("Zênite Fácil - NOVA LEI DE LICITAÇÕES - PRORROGAÇÃO", "Zênite Fácil — prorrogação de ARP e renovação de quantitativos"),
                ("Eventos de alteração em procedimento auxiliar de credenciamento", "Compras.gov.br — eventos de alteração no credenciamento"),
            ],
            "J": [
                ("Acordao TCE-PI 394-A.2026", "Acórdão TCE-PI 394-A/2026 — consulta do MPPI: prorrogação e renovação de quantitativos de ARP"),
                ("TCE Expediente 30.2025", "TCE-PI — decisão plenária (expediente 30/2025)"),
                ("Acórdão TCU nº 547-2026", "Acórdão TCU 547/2026-Plenário — auditoria em SRP e PNCP"),
                ("Nota Recomendatoria Conjunta 01.2025", "Nota Recomendatória Conjunta 01/2025 — adesão a ARP (carona)"),
                ("AGU – Parecer nº 00453-2024", "Parecer AGU 00453/2024 — renovação de quantitativos na prorrogação da ARP"),
                ("PARECER n. 00261-2024", "Parecer AGU 00261/2024/E-CJU/SCOM"),
                ("PARECER Nº 00004-2024-CGEST", "Parecer AGU 00004/2024/CGEST — vitrine de compras e credenciamento"),
                ("MJR 86 - Adesão por ARP", "MPPI — MJR 86/2025 (adesão a ARP)"),
                ("MJR 86 - Análise Preliminar", "MJR 86 — análise preliminar de conformidade"),
                ("MJR 86 - Análise Conclusiva", "MJR 86 — análise conclusiva de conformidade"),
                ("MJR 95 - MANIFESTACAO-JURIDICA", "MPPI — MJR 95/2025 (prorrogação de vigência de ARP)"),
                ("MJR 95 - LISTA_DE_VERIFICACAO", "MJR 95 — lista de verificação"),
                ("MJR 95 - Modelo de Termo Aditivo", "MJR 95 — modelo de termo aditivo de prorrogação de ARP"),
                ("MJR 95 - ANALISE_PRELIMINAR", "MJR 95 — análise preliminar de conformidade"),
                ("MJR 95 - ANALISE_CONCLUSIVA", "MJR 95 — análise conclusiva de conformidade"),
            ],
        },
        "lacunas": [],
    },
    {
        "id": "13", "titulo": "Formalização, gestão e fiscalização do contrato",
        "artigos": "Lei 14.133, arts. 89-95 (formalização); art. 90 (remanescentes); arts. 115-123 (execução; art. 117 fiscalização)",
        "itens": {
            "N": [
                ("Ato PGJ 0462.2013", "Ato PGJ 462/2013 — fiscalização e gestão de contratos no MPPI"),
                ("Resolução TCE-PI 011.2026", "Resolução TCE-PI 11/2026 — gestão e fiscalização de contratos"),
                ("n15.093212013", "Decreto Estadual 15.093/2013 — gestão de contratos"),
                ("Decreto Estadual 23649.2025", "Decreto Estadual 23.649/2025 — ordens de serviço nos contratos"),
                ("n22.089192023", "Decreto Estadual 22.089/2023 — ordens de serviço"),
                ("n16.73722016", "Decreto Estadual 16.737/2016 — publicação de extratos"),
                ("Resolução Estadual - n0022021", "Resolução CGFR 002/2021 — extratos e execução contratual"),
            ],
            "M": [
                ("Contratação Direta/modelo-de-termo-de-contrato-compras", "AGU — termo de contrato: compras (contratação direta)"),
                ("Contratação Direta/modelo-de-termo-de-contrato-servico-com-mao", "AGU — termo de contrato: serviço com DEMO (contratação direta)"),
                ("Contratação Direta/modelo-de-termo-de-contrato-servico-sem-mao", "AGU — termo de contrato: serviço sem DEMO (contratação direta)"),
                ("Contratação Direta/modelo-de-termo-de-contrato-obras", "AGU — termo de contrato: obras e serviços de engenharia (contratação direta)"),
                ("Pregão e Concorrência/Compras/modelo-de-termo-de-contrato-compras", "AGU — termo de contrato: compras (pregão/concorrência)"),
                ("Serviços sem DEMO/modelo-de-termo-de-contrato", "AGU — termo de contrato: serviço sem DEMO (pregão/concorrência)"),
                ("modelo-de-termo-de-contrato-tic-compras", "AGU — termo de contrato: compras de TIC"),
                ("modelo-de-termo-de-contrato-tic-servicos", "AGU — termo de contrato: serviços de TIC"),
                ("Roteiro - Publicacao de Contrato", "MPPI — roteiro de publicação de contrato no site"),
                ("Acompanhamento_Contratos_MPPI_2026", "MPPI — acompanhamento de contratos 2026"),
            ],
            "D": [
                ("Cartilha do Fiscal de Contratos - TCE-PI", "TCE-PI — cartilha do fiscal de contratos"),
                ("Manual IRB-Ibraop - Auditoria de Obras", "IRB/Ibraop — manual de auditoria de obras públicas e serviços de engenharia (2018, anterior à Lei 14.133)"),
                ("Manual completo - Convocação de Remanescentes", "Compras.gov.br — convocação de remanescentes (art. 90)"),
                ("Contratos.gov – Manual operacional de gestão e fiscalização", "Contratos.gov.br — manual operacional de gestão e fiscalização"),
                ("TEMPORÁRIO Manual Contratos Gov.br - Nova Versão - 2.14.0", "Contratos.gov.br — manual da nova versão 2.14.0 (set/2026, provisório)"),
                ("Manual Operacional - Contratos.gov.br - Perfil Fornecedor", "Contratos.gov.br — perfil fornecedor"),
                ("tutorial_dez.25_AlteraodeDocumentoHbil", "Contratos.gov.br — alteração de documento hábil"),
                ("Operacionalização do Sistema - Vanessa", "Material de apoio — operação do Contratos.gov.br (Vanessa Ventura)"),
            ],
            "J": [
                ("Acordao TCE-PI 300.2025 - 1a Camara", "Acórdãos TCE-PI 300 e 300-A/2025-1ª Câmara — adesão a ARP, sobrepreço, falta de suplente do fiscal e de PCA"),
            ],
        },
        "lacunas": [],
    },
    {
        "id": "14", "titulo": "Alterações, prorrogação, reequilíbrio e extinção",
        "artigos": "Lei 14.133, arts. 104-114 (prerrogativas e duração); arts. 124-136 (alterações e reequilíbrio); arts. 137-139 (extinção)",
        "itens": {
            "N": [
                ("n22.737062024", "Decreto Estadual 22.737/2024 — reajuste de preços"),
                ("n19.841062021", "Decreto Estadual 19.841/2021 — reajuste de materiais asfálticos"),
                ("CGE IN 02.2025", "IN CGE-PI 02/2025 — procedimentos em obras"),
                ("Instrução Normativa Estadual - n00012013", "IN CGE-PI 01/2013 — obras: aditivos, cronograma e medições"),
            ],
            "M": [
                ("LV - Prorrogação Contínuos/Lei-14133-Lista-de-Verificacao-Prorrogacao-Servicos-ou-Fornecimentos-Continuos.md", "PGE-PI — LV prorrogação de contínuos"),
                ("LV - Prorrogação Não Contínuos/Lei-14133-Lista-de-Verificacao-Prorrogacao-Obras-Servicos-ou-Fornecimentos-nao-continuados.md", "PGE-PI — LV prorrogação de não contínuos"),
                ("Lei-14133-Lista-de-Verificacao-Alteracao-Quantitativa.md", "PGE-PI — LV alteração quantitativa"),
                ("Lei-14133-Lista-de-Verificacao-Reajuste.md", "PGE-PI — LV reajuste"),
                ("Lei-14133-Lista-de-Verificacao-Repactuacao.md", "PGE-PI — LV repactuação"),
                ("Lei-14133-Lista-de-Verificacao-Revisao-Realinhamento.md", "PGE-PI — LV revisão/realinhamento"),
            ],
            "D": [
                ("ORIENTACAO-TECNICA-REEQUILIBRIO", "Orientação técnica — reequilíbrio econômico-financeiro"),
            ],
            "J": [
                ("PARECER n. 00004-2025-CNLCA", "Parecer AGU 00004/2025/CNLCA"),
                ("PARECER Nº 00005-2025-CNLCA", "Parecer AGU 00005/2025/CNLCA"),
                ("PARECER n. 00005-2025-DECOR", "Parecer AGU 00005/2025/DECOR"),
                ("MJRs_MPPI/MJR 56 - Pedido", "MPPI — MJR 56/2025 (substituição de marca em contrato ou ARP)"),
                ("MJR 56 - Análise Preliminar", "MJR 56 — análise preliminar de conformidade"),
                ("MJR 56 - Análise Conclusiva", "MJR 56 — análise conclusiva de conformidade"),
            ],
        },
        "lacunas": [],
    },
    {
        "id": "15", "titulo": "Sanções administrativas e responsabilização",
        "artigos": "Lei 14.133, arts. 155-163; Lei 12.846/2013",
        "itens": {
            "N": [
                ("Decreto Estadual 22677.2024", "Decreto Estadual 22.677/2024 — responsabilização de pessoas jurídicas (Lei Anticorrupção)"),
                ("Instrução Normativa Estadual - n00012015", "IN CGE-PI 01/2015 — tomada de contas especial e cobrança simplificada"),
            ],
            "M": [
                ("FLUXOGRAMA ATOS PARA A APLICAÇÃO DE SANÇÕES", "Fluxograma dos atos para aplicação de sanções contratuais"),
            ],
            "D": [
                ("TIPOLOGIA DE FRAUDES", "Capítulo de livro — tipologia de fraudes em licitação"),
            ],
            "J": [
                ("PARECERn000022022CPLCdosimetria", "Parecer 00002/2022/CPLC — dosimetria da penalidade contratual"),
            ],
        },
        "lacunas": ["Falta regulamento de sanções do MPPI e um manual de sanções (por exemplo, o do ES)."],
    },
    {
        "id": "16", "titulo": "Liquidação, pagamento e suprimento de fundos",
        "artigos": "Lei 14.133, arts. 141-146; Lei 4.320/1964, arts. 62-69",
        "itens": {
            "N": [
                ("Federal - IN 77.2022", "IN SEGES 77/2022 — ordem cronológica de pagamentos"),
                ("Federal - Lei 4320.1964", "Lei 4.320/1964 — normas gerais de direito financeiro"),
                ("Lei Complementar 101.2000", "LC 101/2000 — Lei de Responsabilidade Fiscal"),
                ("n17.084032017", "Decreto Estadual 17.084/2017 — execução da despesa"),
                ("n22.380052023", "Decreto Estadual 22.380/2023 — execução da despesa"),
                ("Instrução Normativa Estadual - n00012021", "IN SEFAZ/SUTESP 01/2021 — Nota Patrimonial"),
                ("Ato PGJ 1228.2022 - Suprimento de Fundos (Compilado)", "Ato PGJ 1.228/2022 — suprimento de fundos no MPPI (compilado)"),
                ("Ato PGJ 1471.2025", "Ato PGJ 1.471/2025 — altera o Ato 823/2018: Diretor de Sede como agente suprido (Ato 1.228)"),
                ("Decreto Estadual 16226.2015", "Decreto Estadual 16.226/2015 — suprimento de fundos no Executivo"),
            ],
            "M": [
                ("MJR 66 - Pagamento Por Indenização", "MPPI — MJR 66/2025 (pagamento por indenização)"),
                ("MJR 66 - Modelo Termo de Reconhecimento", "MJR 66 — modelo de termo de reconhecimento de dívida"),
                ("MJR 66 - Análise Preliminar", "MJR 66 — análise preliminar de conformidade"),
                ("MJR 66 - Análise Conclusiva", "MJR 66 — análise conclusiva de conformidade"),
            ],
            "D": [
                ("Cartilha de Retencoes Tributarias", "SEFAZ-PI — cartilha de retenções tributárias em contratos e convênios"),
                ("Guia Essencial de Suprimento de Fundos MPPI", "MPPI — guia essencial de suprimento de fundos"),
                ("Manual de Suprimento de Fundos do MPPI 2025", "MPPI — manual de suprimento de fundos 2025"),
                ("Informativo-Suprimento-de-Fundos-Maio", "MPPI — informativo de suprimento de fundos (mai/2024)"),
                ("CGU - GuiaSuprimento", "CGU — guia de suprimento de fundos"),
                ("MANUAL-DE-ADIANTAMENTO-DO-MP-BA", "MP-BA — manual de adiantamento (3ª ed.)"),
                ("MPES - Portaria-n-7.843", "MPES — Portaria 7.843/2015 (suprimento de fundos)"),
                ("MPMG - 1-1-D646", "MPMG — Resolução PGJ 01/2024 (suprimento de fundos)"),
                ("MPRJ - guiarapido", "MPRJ — guia rápido de suprimento de fundos"),
                ("manual_fundo_rotativo_3", "Manual de fundo rotativo"),
                ("34_suprimento_de_fundos_2ed", "Suprimento de fundos, 2ª ed."),
                ("Federal - mto_2026", "MTO 2026 — Manual Técnico de Orçamento federal"),
                ("02_Estadual_PI/Manuais_e_Guias_Tecnicos/manual-tecnico-do-orcamento", "Manual técnico do orçamento — Piauí"),
                ("qdd-2026-mp", "QDD 2026 — Ministério Público"),
                ("loa-2026-lei-8.914.2025", "LOA 2026 do Piauí — Lei 8.914/2025"),
            ],
            "J": [],
        },
        "lacunas": [],
    },
]

TRANSVERSAL = {
    "titulo": "Temas transversais",
    "blocos": [
        ("Transparência, LGPD e acesso à informação", [
            ("Federal Lei 12527.2011", "Lei 12.527/2011 — Lei de Acesso à Informação"),
            ("Decreto Estadual 23003.2024", "Decreto Estadual 23.003/2024 — proteção de dados pessoais no Piauí"),
            ("Cartilha - Acesso a Informação - Atricon", "Atricon — cartilha de acesso à informação"),
            ("Cartilha Portal da Transparencia TCE", "TCE — cartilha do portal da transparência"),
            ("Manual-do-Portal-da-Transparncia", "Manual do portal da transparência, 5ª ed."),
        ]),
        ("Controle externo (TCE-PI) e prestação de informações", [
            ("Instrução Normativa TCE-PI 002.2026", "IN TCE-PI 2/2026 — sistemas Licitações Web, Contratos Web e Obras Web"),
            ("Manual Operacional TCE-PI - Sistema Licitacoes Web", "TCE-PI — manual operacional do Licitações Web"),
            ("Lei Estadual 5888.2009", "Lei Estadual 5.888/2009 — Lei Orgânica do TCE-PI"),
            ("Resolucao TCE-PI nº 37.2024", "Resolução TCE-PI 37/2024 — deliberações e medidas corretivas"),
            ("Mapeamento_Licitacoes_TCE_PI", "Mapeamento de licitações no TCE-PI"),
            ("Achados_TCE-PI_Boletins_2023-2026", "TCE-PI — achados consolidados dos boletins 2023-2026"),
            ("Boletim de Jurisprudencia TCE-PI - Consolidado Anual 2026", "TCE-PI — boletim de jurisprudência, consolidado 2026"),
            ("Boletim de Jurisprudencia TCE-PI - Consolidado Anual 2024", "TCE-PI — boletim de jurisprudência, consolidado 2024"),
            ("Boletim de Jurisprudencia TCE-PI - Consolidado Anual 2022", "TCE-PI — boletim de jurisprudência, consolidado 2022"),
            ("00_PAINEL_CONSOLIDADO_JURISPRUDENCIA_TCE_PI", "TCE-PI — painel consolidado dos informativos de julgamento"),
            ("01_Licitacoes_e_Contratos_Julgados_TCE_PI", "TCE-PI — julgados sobre licitações e contratos"),
            ("02_Denuncias_Licitacoes_e_Fraudes_TCE_PI", "TCE-PI — denúncias sobre licitações e fraudes"),
            ("05_Representacoes_Licitantes_TCE_PI", "TCE-PI — representações de licitantes"),
            ("Boletim Guia Lici - Consolidado Anual 2026", "Guia Lici — boletim consolidado 2026"),
            ("Boletim Guia Lici - Consolidado Anual 2025", "Guia Lici — boletim consolidado 2025"),
        ]),
        ("PNCP, APIs e dados abertos", [
            ("Manual_integracao_pncp", "PNCP — manual de integração"),
            ("API de dados abertos do Compras.gov.br", "Compras.gov.br — manual da API de dados abertos (fev/2026)"),
            ("manual-api-compras", "Manual da API de compras"),
        ]),
        ("Auditoria e boas práticas", [
            ("NOTA TÉCNICA CONJUNTA ATRICON-IRB", "Nota Técnica Conjunta Atricon-IRB 01/2026"),
            ("Norma Internacional ISSAI 100", "ISSAI 100 — princípios fundamentais de auditoria do setor público"),
            ("Slides - 50 Erros", "Slides — 50 erros mais comuns em licitações"),
            ("TCE-RS – Conclusões Técnicas", "TCE-RS — conclusões técnicas sobre a nova lei para a fiscalização"),
        ]),
        ("Inteligência artificial aplicada", [
            ("Prompts - Notebook LM", "Prompts para NotebookLM"),
            ("Prompts - Apresentacao e Descricao do Cenario", "Prompts — apresentação e descrição do cenário"),
            ("Guia Pratico de Prompt e Pesquisa com IA", "Governo Digital — guia prático de prompt e pesquisa com IA"),
            ("ia-generativa-no-servico-publico", "IA generativa no serviço público"),
            ("Cartilha Zenite - 5 Erros", "Zênite — 5 erros com IA nas contratações públicas"),
            ("Slides - IA Aplicada nas Licitações", "Slides — IA aplicada nas licitações"),
            ("Palestra Tecnica - Aplicacoes e Limitacoes", "Palestra — aplicações e limitações de IA no controle externo"),
        ]),
    ],
}

POR_OBJETO = {
    "titulo": "Por tipo de objeto",
    "blocos": [
        ("TIC", [
            ("Resolucao-CNMP-n-283", "Resolução CNMP 283 — contratações de TIC no MP"),
            ("Contratações de TI – Visão Geral", "CNMP — contratações de TI: visão geral"),
            ("Contratações de TI – Planejamento", "CNMP — contratações de TI: planejamento"),
            ("Contratações de TI-Seleção", "CNMP — contratações de TI: seleção de fornecedores"),
            ("Contratações de TI – Gestão", "CNMP — contratações de TI: gestão do contrato"),
            ("MOTec", "CNMP — MOTec"),
            ("n032020112020", "Nota Técnica TCE-PI 03/2020 — contratação de soluções de TIC"),
            ("Ato PGJ 939.2019", "Ato PGJ 939/2019 — atividades de TI no MPPI"),
            ("Portaria PGJ 2065.2026", "Portaria PGJ 2.065/2026 — equipe de planejamento de TIC"),
            ("Portaria PGJMPPI - n3447.0", "Portaria PGJ 3.447/2024 — designações de TIC"),
            ("Portaria PGJMPPI - n4335.0", "Portaria PGJ 4.335/2024 — designações de TIC"),
            ("Instrumento_de_Padronizao_AGU_TIC", "AGU — instrumento de padronização para TIC"),
            ("Manual de Contratação de TIC sob a Ótica", "Manual de contratação de TIC sob a ótica da nova lei"),
        ]),
        ("Obras e serviços de engenharia", [
            ("Decreto Estadual 21909.2023", "Decreto Estadual 21.909/2023 — obras e serviços de engenharia"),
            ("Cartilha_Minuta_do_IPPC_Engenharia", "AGU — instrumento de padronização: obras e engenharia"),
            ("Obras e Serviços de Engenharia/modelo-de-termo-de-contrato-obras", "AGU — termo de contrato de obras (pregão/concorrência)"),
        ]),
        ("Terceirização e mão de obra exclusiva", [
            ("Federal - IN 05.2017", "IN SEGES 05/2017 — serviços terceirizados"),
            ("Nota Técnica TCE-PI 001.2025", "Nota Técnica TCE-PI 01/2025 — contratações temporárias e terceirizações"),
            ("Ato PGJ 1449.2024", "Ato PGJ 1.449/2024 — reserva de vagas para mulheres em vulnerabilidade"),
            ("Estudo Temático do TCE-MG (fev-2025)", "TCE-MG — estudo temático sobre terceirização"),
            ("n14.483262011", "Decreto Estadual 14.483/2011 — terceirização"),
            ("GUIAREEMBOLSOCRECHE", "Guia — reembolso-creche em contratos com DEMO"),
            ("Serviços com Demo/modelo-de-termo-de-contrato", "AGU — termo de contrato com DEMO (pregão/concorrência)"),
        ]),
        ("Imóveis", [
            ("Federal - IN 103.2022", "IN SEGES 103/2022 — locação de imóveis"),
            ("POP - Inexigibilidade - Locacao de Imoveis", "MPPI — POP locação de imóveis (POP-CLC-08)"),
            ("PARECER n. 00880-2023", "Parecer AGU 00880/2023/E-CJU/SCOM"),
            ("Lei-14133-Lista-de-Verificacao-Locacao-Imovel", "PGE-PI — LV locação de imóvel"),
            ("Minuta-Padrao-Contrato-de-Locacao", "PGE-PI — minuta-padrão de contrato de locação"),
            ("Lei Estadual - n7.612272021", "Lei Estadual 7.612/2021 — gestão de imóveis do Estado"),
            ("Federal - IN 98.2025 SPU", "IN SPU/MGI 98/2025 — destinação e gestão de imóveis da União"),
            ("Termo_de_Cessao_Gratuita", "PGE-PI — termo de cessão gratuita de uso de imóvel"),
            ("Decreto Estadual 23269.2024", "Decreto Estadual 23.269/2024 — doação de bens móveis e serviços"),
        ]),
        ("Sustentabilidade", [
            ("n13.701052009", "Decreto Estadual 13.701/2009 — compras sustentáveis"),
            ("n23.891122025", "Decreto Estadual 23.891/2025 — sustentabilidade"),
            ("GUIANACIONALDECONTRATACOESSUSTENTAVEIS2024", "AGU — Guia Nacional de Contratações Sustentáveis 2024"),
            ("guia-de-contratacoes-sustentaveis-set-2023", "Guia de contratações sustentáveis (set/2023)"),
            ("Conselho Superior da Justiça do Trabalho", "CSJT — guia de contratações sustentáveis, 4ª ed."),
        ]),
        ("Inovação", [
            ("Biblioteca_Manuais_e_Cursos/Compras_publicas_para_inovacao", "Compras públicas para inovação no Brasil"),
            ("Jornada de Compras Publicas de Inovacao", "Jornada de compras públicas de inovação"),
            ("INOVAGOV SC", "INOVAGOV SC — planejamento de contratações de inovação"),
            ("TCU - Edital 001.2024", "TCU — edital de licitação especial para solução inovadora"),
        ]),
        ("Publicidade, eventos e patrocínio", [
            ("Manual completo - Concorrências Presenciais Lei 12.232", "Compras.gov.br — concorrências presenciais (Lei 12.232/2010)"),
            ("n21.813092023", "Decreto Estadual 21.813/2023 — publicidade"),
            ("n21.812092023", "Decreto Estadual 21.812/2023 — publicidade"),
            ("Nota Técnica TCE-PI 002.2024", "Nota Técnica TCE-PI 02/2024 — despesas com festas, shows e artistas"),
            ("Decreto Estadual 22822.2024", "Decreto Estadual 22.822/2024 — patrocínio"),
            ("n16.266032015", "Decreto Estadual 16.266/2015 — publicidade/eventos"),
            ("Guia_boas_praticas_contratacoes_publicas_publicidade", "Guia de boas práticas em contratações de publicidade"),
        ]),
        ("Veículos e passagens", [
            ("n14.386182011", "Decreto Estadual 14.386/2011 — veículos"),
            ("n14.891112012", "Decreto Estadual 14.891/2012 — passagens/veículos"),
            ("PARECER Nº 00015-2024-CNLCA", "Parecer AGU 00015/2024/CNLCA"),
        ]),
    ],
}
