META = {
    'TAPP-D - Nota Tecnica de Revisao da Minuta (02.09.2026).docx': dict(
        tipo='Nota Técnica', numero='', ano=2026, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Revisão da minuta do TAPP-D (Termo de Análise Preliminar da Contratação Direta por Dispensa, art. 75, I e II, da Lei nº 14.133/2021)',
        status='Documento de trabalho (02/09/2026)',
        tags=['tapp-d', 'tapp', 'dispensa', 'art-75-i-ii', 'mjr-92-2024', 'analise-preliminar', 'nota-tecnica', 'assessoria-de-compras', 'mppi'],
        titulo='Nota Técnica de Revisão da Minuta do TAPP-D — Assessoria de Compras (02/09/2026)',
        ementa='Nota técnica da Assessoria de Compras da CLC/MPPI que revisa os produtos elaborados para adaptar o TAPP da Assessoria de Licitações às contratações diretas por dispensa (art. 75, I e II): o diagnóstico com a matriz comparativa e a minuta do TAPP-D. Registra o que já está bem resolvido (controle de fracionamento em seção própria, separação entre estimativa da despesa e justificativa de preço, ETP e Análise de Riscos tratados como pergunta-filtro, blocos condicionais para SRP, engenharia e TIC) e nove achados com fundamento e sugestão, entre eles a ausência do DAP no checklist, a falta de verificação do instrumento contratual, o Ato PGJ/PI nº 1414/2024 citado sem a alteração posterior, o valor desatualizado da exceção de fracionamento para manutenção veicular e a falta de correspondência entre o quadro-resumo e a conclusão (A/B/C). Fecha com o encaminhamento sugerido. Par do documento "TAPP-D - Diagnóstico e Matriz de Notas".'),
    'POP - Contratacao por Dispensa de Licitacao (POP-CLC-02, rev. 05.02.2025).docx': dict(
        tipo='Procedimento Operacional Padrão (POP)', numero='POP-CLC-02', ano=2025, orgao='MPPI / CLC', ambito='MPPI (interno)',
        assunto='Procedimento de contratação por dispensa de licitação (bens e serviços), com checklist de instrução',
        status='Em uso (revisão nº 03, de 05/02/2025)',
        tags=['pop', 'pop-clc-02', 'dispensa', 'art-75', 'contratacao-direta', 'checklist', 'clc', 'mppi'],
        titulo='POP-CLC-02 — Contratação por Dispensa de Licitação: Bens e Serviços (rev. 05/02/2025)',
        ementa='Manual de procedimento da Coordenadoria de Licitações e Contratos do MPPI para a contratação por dispensa de bens e serviços: recursos e documentos necessários, normativos de referência (Lei nº 14.133/2021, IN 65/2021, IN 67/2021, IN 58/2022, IN 81/2022 e Decreto Estadual nº 21.872/2023), equipe necessária, passos críticos por fase e responsável, providências pós-contratação (extrato, portaria de fiscalização, PNCP, cadastro no TCE-PI em 10 dias úteis, remessa à Assessoria de Gestão de Contratos) e checklist de instrução (DOD, TR, pesquisa de preços, pareceres, autorização e nota de empenho, contrato). Elaborado em 03/05/2024; revisão nº 03 de 05/02/2025.'),
    'POP - Inexigibilidade - Locacao de Imoveis (POP-CLC-08).docx': dict(
        tipo='Procedimento Operacional Padrão (POP)', numero='POP-CLC-08', ano=2024, orgao='MPPI / CLC', ambito='MPPI (interno)',
        assunto='Procedimento de contratação por inexigibilidade para locação de imóveis (art. 74, V, da Lei nº 14.133/2021), com checklist de instrução',
        status='Em uso (revisão nº 02, de 31/07/2024)',
        tags=['pop', 'pop-clc-08', 'inexigibilidade', 'locacao-de-imoveis', 'art-74-v', 'in-103-2022', 'contratacao-direta', 'checklist', 'clc', 'mppi'],
        titulo='POP-CLC-08 — Inexigibilidade: Locação de Imóveis (art. 74, V, da Lei nº 14.133/2021)',
        ementa='Manual de procedimento da CLC/MPPI para a contratação por inexigibilidade na locação de imóveis (art. 74, V, da Lei nº 14.133/2021): recursos necessários, documentos de referência (incluindo a IN SEGES nº 103/2022, sobre locação de imóveis), equipe necessária, passos críticos por fase e responsável, providências pós-contratação (extrato, portaria de fiscalização, PNCP, cadastro no TCE-PI, remessa à Assessoria de Gestão de Contratos) e checklist de instrução. Elaborado em 03/05/2024; revisão nº 02 de 31/07/2024.'),
    'Roteiro - Dispensa sem Disputa.docx': dict(
        tipo='Roteiro de Procedimento', numero='', ano=2025, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Roteiro passo a passo da contratação por dispensa sem disputa, da unidade demandante ao envio do contrato para a gestão',
        status='Em uso (versão de 18/08/2025)',
        tags=['roteiro', 'dispensa', 'dispensa-sem-disputa', 'art-75', 'fluxo-processual', 'pncp', 'tce-pi', 'assessoria-de-compras', 'mppi'],
        titulo='Roteiro — Contratação por Dispensa sem Disputa (fluxo da CLC/MPPI)',
        ementa='Etapas numeradas da dispensa sem disputa no MPPI, agrupadas por responsável: unidade demandante (PCA, DFD, ETP ou justificativa, Análise de Riscos, TR, pesquisa de preços conforme IN 65/2021, mapa comparativo, portaria da equipe, MJR, Análise Preliminar de Conformidade e lista de verificação); análise inicial da Assessoria de Compras e pareceres da CCF e da ASSPGO; segunda análise (minuta contratual, manifestação de conformidade da MJR, Atos PGJ nº 1383/2024 e 1480/2025 que dispensam os pareceres jurídico e da Controladoria, aprovação dos artefatos, aviso no site por 3 dias, sobrestamento do art. 75, § 3º, cadastros no PNCP e no Licitações Web do TCE-PI, autorização para contratar e empenhar); nota de empenho; e fase final (contrato, publicações no DOEMPI, PNCP, TCE-PI e site, fiscalização e remessa à Assessoria de Gestão de Contratos).'),
    'Roteiro - Inexigibilidade.docx': dict(
        tipo='Roteiro de Procedimento', numero='', ano=2025, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Roteiro passo a passo da contratação por inexigibilidade, da unidade demandante ao envio do contrato para a gestão',
        status='Em uso (versão de 01/08/2025)',
        tags=['roteiro', 'inexigibilidade', 'art-74', 'contratacao-direta', 'fluxo-processual', 'pncp', 'tce-pi', 'assessoria-de-compras', 'mppi'],
        titulo='Roteiro — Contratação por Inexigibilidade (fluxo da CLC/MPPI)',
        ementa='Etapas numeradas da contratação por inexigibilidade no MPPI, com a mesma estrutura do roteiro da dispensa sem disputa (unidade demandante, análises da Assessoria de Compras, pareceres da CCF e da ASSPGO, nota de empenho e fase final de contrato, publicações e fiscalização), mas sem a publicação de aviso para novas propostas e o sobrestamento do art. 75, § 3º, que são próprios da dispensa.'),
    'Roteiro - Contratacao por ARP.docx': dict(
        tipo='Roteiro de Procedimento', numero='', ano=2025, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Sequência de documentos da contratação decorrente de ata de registro de preços própria',
        status='Em uso (versão de 23/04/2025)',
        tags=['roteiro', 'ata-de-registro-de-precos', 'srp', 'contratacao-por-arp', 'empenho', 'publicacao', 'mppi'],
        titulo='Roteiro — Contratação por Ata de Registro de Preços (sequência de documentos)',
        ementa='Lista curta da sequência de documentos de uma contratação por ARP no MPPI: enquadramento da contratação, acompanhamento da ARP, memória de cálculo, parecer orçamentário e financeiro, autorização de empenho, cadastro no Siafe, nota de empenho, certidões, contrato, publicações no DOEMPPI, PNCP e TCE-PI (prazo de 10 dias úteis), fiscalização (ofício, portaria e ciência) e publicação no site do MPPI. Complementa o POP-CLC-05.'),
    'Roteiro - Dispensa Eletronica.docx': dict(
        tipo='Roteiro de Procedimento', numero='', ano=2025, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Sequência de documentos da contratação por dispensa eletrônica',
        status='Em uso (versão de 23/04/2025)',
        tags=['roteiro', 'dispensa-eletronica', 'art-75', 'in-67-2021', 'contratacao-direta', 'fluxo-processual', 'mppi'],
        titulo='Roteiro — Contratação por Dispensa Eletrônica (sequência de documentos)',
        ementa='Lista da sequência de documentos de uma dispensa eletrônica no MPPI: análise inicial da Assessoria de Compras e ajustes, parecer orçamentário e financeiro, portaria dos agentes de contratação, minuta contratual, modelo de proposta, minuta e publicação do aviso de contratação direta, atos PGJ que dispensam os pareceres da Controladoria e jurídico, manifestação de conformidade da MJR, aprovação dos artefatos, anexos da sessão (proposta, habilitação, análise técnica, relatórios de declarações e da dispensa), homologação, parecer dos agentes, empenho, contrato, ciência da fiscalização e publicações (extrato, PNCP, TCE-PI e site).'),
    'Roteiro - Dispensa (lista de documentos 2024).docx': dict(
        tipo='Roteiro de Procedimento', numero='', ano=2024, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Lista de documentos da instrução de uma dispensa (versão de 2024)',
        status='Histórico (versão de 11/12/2024; ver roteiros de 2025)',
        tags=['roteiro', 'dispensa', 'lista-de-documentos', 'instrucao-processual', 'mppi'],
        titulo='Roteiro — Dispensa: lista de documentos da instrução (2024)',
        ementa='Lista simples, de dezembro de 2024, dos documentos que compõem a instrução de uma dispensa no MPPI: DFD, ETP, mapa de riscos, TR, mapa comparativo de preços, pareceres orçamentário e financeiro, minuta contratual, habilitação, pareceres da Controladoria Interna e jurídico (ou sua dispensa), portarias dos agentes de contratação, aprovação dos artefatos, autorização para contratar e empenhar e etapas seguintes. Versão anterior aos roteiros de 2025 de dispensa sem disputa e dispensa eletrônica.'),
    'Roteiro - Liberacao de ARP para Adesao.docx': dict(
        tipo='Roteiro de Procedimento', numero='', ano=2025, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Liberação de ata de registro de preços do MPPI para adesão por outro órgão (carona) e registro no Licitações Web do TCE-PI',
        status='Em uso (versão de 30/05/2025)',
        tags=['roteiro', 'ata-de-registro-de-precos', 'adesao', 'carona', 'orgao-gerenciador', 'licitacoes-web', 'tce-pi', 'mppi'],
        titulo='Roteiro — Liberação de ARP do MPPI para Adesão (carona)',
        ementa='Passos do MPPI como órgão gerenciador ao liberar a adesão de outro órgão à sua ata: tela "Analisar Solicitação de Adesão", documentos exigidos do órgão aderente (justificativa de preços, justificativa da contratação, justificativa para aquisição isolada de item de grupo e aceite do fornecedor) e registro das adesões no sistema Licitações Web do TCE-PI (menu Gerenciar SRP, pregão, ARP, lotes, itens e quantitativos aderidos).'),
    'Roteiro - Adesao a ARP no Compras.gov.docx': dict(
        tipo='Roteiro de Procedimento', numero='', ano=2025, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Solicitação de adesão a ata de registro de preços no módulo Gestão da Ata SRP do Compras.gov.br',
        status='Em uso (versão de 02/04/2025)',
        tags=['roteiro', 'ata-de-registro-de-precos', 'adesao', 'compras-gov', 'gestao-da-ata-srp', 'manual-de-sistema'],
        titulo='Roteiro — Adesão a ARP no Compras.gov.br (Gestão da Ata SRP)',
        ementa='Passo a passo curto, com capturas de tela, para solicitar adesão a ata no Compras.gov.br: acesso ao módulo Gestão da Ata SRP, menu Adesão > Solicitar e dados de pesquisa (UASG, órgão, pregão e número da ARP), com um exemplo preenchido de ata da PGJ/PI.'),
    'Glossario de Mensagens - Sessao Publica de Pregao.docx': dict(
        tipo='Modelo de Mensagens (Sessão Pública)', numero='', ano=2025, orgao='MPPI / CLC', ambito='MPPI (interno)',
        assunto='Mensagens-padrão do agente de contratação/pregoeiro no chat da sessão pública (pregão e dispensa eletrônica)',
        status='Em uso (versão de 22/07/2025)',
        tags=['pregao-eletronico', 'dispensa-eletronica', 'sessao-publica', 'chat', 'negociacao', 'exequibilidade', 'desclassificacao', 'agente-de-contratacao', 'modelo'],
        titulo='Glossário de Mensagens — Sessão Pública de Pregão e Dispensa Eletrônica',
        ementa='Coletânea de mensagens prontas para o chat da sessão pública: abertura e retomada das etapas de julgamento e habilitação, suspensão e reabertura da sessão, negociação de item, pedido de proposta reajustada, diligência para comprovar a exequibilidade quando o valor for inferior a 50% do orçado e desclassificação por não envio da proposta, com remissão aos subitens do aviso de dispensa.'),
    'Roteiro - Publicacao de Contrato no Site do MPPI.docx': dict(
        tipo='Roteiro de Procedimento', numero='', ano=2025, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Publicação de contrato e de seu extrato na página de Licitações e Contratos do site do MPPI',
        status='Em uso (versão de 20/08/2025)',
        tags=['roteiro', 'publicacao', 'site-mppi', 'transparencia', 'extrato-de-contrato', 'intranet', 'mppi'],
        titulo='Roteiro — Publicação de Contrato no Site do MPPI',
        ementa='Passo a passo, com capturas de tela, para publicar contratos e equivalentes na página de Licitações e Contratos do site do MPPI pela intranet (pasta da CLC, ano e campos do formulário), com um modelo de texto do extrato (contratado, objeto, fundamentação legal, referência ao processo e à dispensa, valor, vigência e equipe de fiscalização). Nomes e matrículas dos fiscais do exemplo foram substituídos por marcadores no .md.'),
    'Prompt Revisor - TR.docx': dict(
        tipo='Prompt de IA (Revisão de Artefato)', numero='', ano=2025, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Prompt-guia para revisão e autochecagem de Termo de Referência por quesitos',
        status='Em uso (versão de 15/07/2025)',
        tags=['prompt', 'ia', 'termo-de-referencia', 'revisao', 'autochecagem', 'checklist', 'lei-14133', 'decreto-21872-2023'],
        titulo='Prompt Revisor — Termo de Referência (revisão e autochecagem)',
        ementa='Prompt para que a IA (ou o revisor) analise um Termo de Referência quesito a quesito, com base na Lei nº 14.133/2021, no Decreto Estadual nº 21.872/2023 e em boas práticas: instruções de uso (conformidade, setor responsável, observações e data; justificativa obrigatória para respostas negativas ou parciais), estrutura de cada quesito, lista de quesitos de verificação, exemplo prático de preenchimento e orientações de finalização.'),
    'Prompt Revisor - TR - Quesitos por Artigo.docx': dict(
        tipo='Prompt de IA (Revisão de Artefato)', numero='', ano=2025, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Prompt-guia para revisão de Termo de Referência com quesitos organizados por dispositivo legal',
        status='Em uso (versão de 16/07/2025)',
        tags=['prompt', 'ia', 'termo-de-referencia', 'revisao', 'lei-14133-art-6-xxiii', 'lei-14133-art-40', 'decreto-21872-2023-art-36', 'srp', 'amostra', 'prova-de-conceito'],
        titulo='Prompt Revisor — Termo de Referência (quesitos por artigo)',
        ementa='Variante do Prompt Revisor do TR em que os quesitos seguem os dispositivos legais: art. 6º, XXIII, e art. 40, § 1º, da Lei nº 14.133/2021; checklist de conformidade do art. 36 do Decreto Estadual nº 21.872/2023; checklist específico do TR para Sistema de Registro de Preços (art. 36, § 1º); quesitos sobre amostras, exame de conformidade e prova de conceito; e quesitos adicionais sugeridos, com exemplo prático e finalização.'),
    'Prompt Revisor - ETP.docx': dict(
        tipo='Prompt de IA (Revisão de Artefato)', numero='', ano=2025, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Prompt-guia para revisão e autochecagem de Estudo Técnico Preliminar (ETP)',
        status='Em uso (versão de 15/07/2025)',
        tags=['prompt', 'ia', 'etp', 'estudo-tecnico-preliminar', 'revisao', 'autochecagem', 'lei-14133-art-18', 'decreto-21872-2023'],
        titulo='Prompt Revisor — Estudo Técnico Preliminar (revisão e autochecagem)',
        ementa='Prompt para que a IA (ou o revisor e a unidade demandante) analise um ETP quesito a quesito, conferindo as exigências legais, normativas e de boas práticas do planejamento das contratações no MPPI: objetivo, instruções de uso (conformidade, setor responsável, observações e data), estrutura de cada quesito, lista de quesitos de verificação, exemplo prático de preenchimento e finalização.'),
    'Prompt Revisor - DFD.docx': dict(
        tipo='Prompt de IA (Revisão de Artefato)', numero='', ano=2025, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Prompt para análise crítica do Documento de Formalização da Demanda (DFD)',
        status='Em uso (versão de 15/07/2025)',
        tags=['prompt', 'ia', 'dfd', 'documento-de-formalizacao-da-demanda', 'revisao', 'lei-14133-art-72-i', 'decreto-21872-2023-art-20'],
        titulo='Prompt Revisor — Documento de Formalização da Demanda (DFD)',
        ementa='Prompt com perguntas para a análise crítica do DFD, com base na Lei nº 14.133/2021, no Decreto Estadual nº 21.872/2023, no parecer jurídico referencial, nos modelos da AGU e nas orientações do MPPI, organizadas por tema: fundamentação legal (art. 72, I, da Lei e art. 20 do Decreto), competência e autoria, descrição da necessidade, estimativa de quantitativos e demais requisitos do documento.'),
    'Prompts - Contratacao Direta (art. 72).docx': dict(
        tipo='Prompt de IA (Redação de Justificativas)', numero='', ano=2024, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Prompts para redigir justificativas da contratação direta (art. 72, I, VI e VII, e art. 75 da Lei nº 14.133/2021)',
        status='Em uso (versão de 21/08/2024)',
        tags=['prompt', 'ia', 'contratacao-direta', 'lei-14133-art-72', 'lei-14133-art-75', 'justificativa', 'razao-da-escolha', 'justificativa-de-preco', 'licitacao-deserta', 'licitacao-fracassada'],
        titulo='Prompts — Justificativas da Contratação Direta (arts. 72 e 75 da Lei nº 14.133/2021)',
        ementa='Conjunto de prompts para gerar textos de instrução da contratação direta: justificativa para afastar os documentos "se for o caso" do art. 72, I (ETP, análise de riscos, TR, projeto básico ou executivo) em objetos de baixa complexidade e valor; razão da escolha do contratado (art. 72, VI); justificativa de preço (art. 72, VII); modelos de encaminhamento da dispensa por licitação deserta ou fracassada (art. 75, III); e justificativas para hipóteses do art. 75, IV.'),
    'Prompts - Notebook LM.docx': dict(
        tipo='Prompt de IA (Configuração de Assistente)', numero='', ano=2026, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Prompt de papel e de análise de DFD para uso no NotebookLM',
        status='Em uso (versão de 05/02/2026)',
        tags=['prompt', 'ia', 'notebooklm', 'persona', 'dfd', 'auditoria-de-processos', 'lei-14133'],
        titulo='Prompts — NotebookLM (papel do assistente e análise de DFD)',
        ementa='Prompt curto para configurar o NotebookLM: define o papel do assistente como assessor de compras do MPPI especialista em licitações e auditoria de processos com base na Lei nº 14.133/2021, e indica o prompt de análise do DFD. O nome do servidor foi substituído por marcador no .md (o .docx original não foi alterado).'),
    'Prompts - Apresentacao e Descricao do Cenario.docx': dict(
        tipo='Prompt de IA (Configuração de Assistente)', numero='', ano=2025, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Prompts de apresentação (persona de especialista em contratações) e modelo de descrição de cenário para consulta à IA',
        status='Em uso (versão de 03/07/2025)',
        tags=['prompt', 'ia', 'persona', 'descricao-de-cenario', 'ocorrencias-impeditivas-indiretas', 'adesao', 'ata-de-registro-de-precos', 'fraude'],
        titulo='Prompts — Apresentação do Especialista e Descrição do Cenário',
        ementa='Dois prompts de apresentação que definem a IA como especialista em contratações públicas do MPPI (ETP, TR, riscos, contratação direta e marco das startups e da inovação: LC nº 182/2021, Lei nº 10.973/2004 e Decreto nº 9.283/2018) e um modelo de descrição de cenário (órgão, objeto, situação atual e tarefa), exemplificado com a verificação de possível fraude apontada em Relatório de Ocorrências Impeditivas Indiretas antes de uma adesão a ata. O nome da empresa do caso foi substituído por marcador no .md.'),
    'Checklist Detalhado do TR (rascunho).docx': dict(
        tipo='Lista de Verificação (Checklist)', numero='', ano=2025, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno)',
        assunto='Checklist detalhado do Termo de Referência, com base legal por item (rascunho)',
        status='Rascunho (versão de 15/07/2025)',
        tags=['checklist', 'termo-de-referencia', 'lei-14133-art-6-xxiii', 'lei-14133-art-40', 'in-81-2022', 'decreto-21872-2023', 'rascunho'],
        titulo='Checklist Detalhado do Termo de Referência (rascunho)',
        ementa='Rascunho de lista de verificação do TR em 25 temas (existência e forma, padronização, equipe de elaboração, necessidade e vínculo com o ETP, definição e especificação do objeto, solução global, modelo de execução, parcelamento, valor estimado e orçamento sigiloso, critérios de julgamento, garantias, qualificação, obrigações, subcontratação, gestão e fiscalização, medição e pagamento, prazos, riscos, elementos do art. 37 do Decreto Estadual nº 21.872/2023, sustentabilidade, engenharia e SRP), com a base legal de cada item na Lei nº 14.133/2021, na IN SEGES/ME nº 81/2022 e no Decreto Estadual nº 21.872/2023.'),
    'TAPP DIMPLANC 004_2025-0 (AMCS) - Empresa Grafica - MPPE.docx': dict(
        tipo='Modelo de Análise Preliminar (TAPP)', numero='004/2025-0', ano=2025, orgao='MPPE — Divisão Ministerial de Planejamento das Contratações (DIMPLANC)', ambito='MPPE (referência externa)',
        assunto='Termo de Análise Preliminar do Planejamento da Contratação — serviço gráfico (versão inicial, com pedido de ajustes)',
        status='Documento-modelo de outro órgão',
        tags=['tapp', 'mppe', 'dimplanc', 'analise-preliminar', 'planejamento-da-contratacao', 'etp', 'termo-de-referencia', 'pregao-eletronico', 'modelo-externo'],
        titulo='TAPP DIMPLANC nº 004/2025-0 (MPPE) — Empresa Gráfica: análise inicial com ajustes',
        ementa='Termo de Análise Preliminar do Planejamento da Contratação emitido pela DIMPLANC do MPPE sobre a contratação de empresa gráfica (pregão eletrônico, valor estimado de R$ 48.200,00). Confere os artefatos (DOD, ETP, análise de riscos, TR, valor estimado e lista de verificação consolidada), analisa cada exigência em tabelas e conclui pela necessidade de ajustes e complementações antes da aprovação do planejamento. Referência do MPPE usada como modelo para o TAPP do MPPI; ver também a versão 004/2025-1.'),
    'TAPP DIMPLANC 004_2025-1 (AMCS) - Empresa Grafica - MPPE.docx': dict(
        tipo='Modelo de Análise Preliminar (TAPP)', numero='004/2025-1', ano=2025, orgao='MPPE — Divisão Ministerial de Planejamento das Contratações (DIMPLANC)', ambito='MPPE (referência externa)',
        assunto='Termo de Análise Preliminar do Planejamento da Contratação — serviço gráfico (reanálise após os ajustes)',
        status='Documento-modelo de outro órgão',
        tags=['tapp', 'mppe', 'dimplanc', 'analise-preliminar', 'planejamento-da-contratacao', 'etp', 'termo-de-referencia', 'pregao-eletronico', 'modelo-externo'],
        titulo='TAPP DIMPLANC nº 004/2025-1 (MPPE) — Empresa Gráfica: reanálise com prosseguimento',
        ementa='Reanálise da DIMPLANC do MPPE sobre a mesma contratação de empresa gráfica após o saneamento dos pontos da versão 004/2025-0: confere os artefatos revisados, registra a atribuição da autoridade competente pelo limite de alçada e recomenda o prosseguimento do rito da contratação. Útil para comparar a análise inicial com a reanálise.'),
    'Checklist padronizado - Fase de planejamento da contratação (consolidado) - versão 2.0.xlsx': dict(
        tipo='Lista de Verificação (Checklist)', numero='2.0', ano=2023, orgao='MPPE', ambito='MPPE (referência externa)',
        assunto='Lista de verificação consolidada da etapa de planejamento da contratação (DOD, ETP e TR)',
        status='Documento-modelo de outro órgão (versão 2.0, maio/2023)',
        tags=['checklist', 'lista-de-verificacao', 'mppe', 'planejamento-da-contratacao', 'dod', 'etp', 'termo-de-referencia', 'modelo-externo'],
        titulo='Checklist Padronizado da Fase de Planejamento da Contratação — MPPE (v. 2.0)',
        ementa='Planilha do MPPE com a lista de verificação consolidada da etapa de planejamento: identificação da solução, da unidade demandante e da equipe de planejamento, itens de verificação por documento (DOD, ETP e TR) e notas explicativas, com a natureza de cada exigência (obrigatória ou condicional), a observância e a indicação do documento em que foi atendida. Inclui a aba de orientações de preenchimento e a aba oculta de validação de dados. É a "lista de verificação consolidada" referida nos TAPPs da DIMPLANC.'),
    'Anexo_1204260_MAPA_DE_RISCOS___Licitacoes_e_Contratos.xlsx': dict(
        tipo='Lista de Verificação (Checklist)', numero='', ano=2025, orgao='CNMP — Comissão de Controle Administrativo e Financeiro (CCAF)', ambito='Nacional / MP',
        assunto='Listas de verificação e mapa de riscos para todas as fases da contratação (ETP, TR, pesquisa de preços, licitação, contratação direta, contrato, alterações, sanções, fiscalização e pagamento)',
        status='Em uso como referência (versão xx/2025)',
        tags=['checklist', 'lista-de-verificacao', 'mapa-de-riscos', 'cnmp', 'ccaf', 'etp', 'termo-de-referencia', 'pesquisa-de-precos', 'contratacao-direta', 'fiscalizacao', 'pagamento', 'sancoes'],
        titulo='Mapa de Riscos e Listas de Verificação de Licitações e Contratos — CNMP/CCAF',
        ementa='Planilha de listas de verificação elaborada pela Comissão de Controle Administrativo e Financeiro do CNMP e juntada ao SEI do MPPI (documento 1204260). Cada aba cobre uma fase (Mapa ETP, Mapa TR, Pesquisa de Preços, Mapa Licitação, Fase Externa, Contratação Direta, Contrato, Alteração Contratual, Sanções, Mapa Fiscalização e Pagamento), com itens numerados, sua fundamentação legal (Lei nº 14.133/2021, INs SEGES, decretos federais e jurisprudência) e colunas de conformidade, setor responsável, observações e data. Inclui modelo de preenchimento.'),
    'TAPP-D - Diagnostico e Matriz de Notas (02.09.2026).pdf': dict(
        tipo='Documento de Estudo / Planejamento', numero='', ano=2026, orgao='MPPI / CLC', ambito='MPPI (interno)',
        assunto='Adaptação do TAPP às contratações diretas por dispensa (art. 75, I e II): diagnóstico, matriz de requisitos da MJR nº 92/2024, notas de parametrização e pontos de atenção',
        status='Documento de trabalho (02/09/2026)',
        tags=['tapp-d', 'tapp', 'dispensa', 'art-75-i-ii', 'mjr-92-2024', 'analise-preliminar', 'matriz-de-requisitos', 'agente-de-contratacao', 'mppi'],
        titulo='TAPP-D — Diagnóstico e Matriz de Notas para a Adaptação do TAPP à Dispensa (02/09/2026)',
        ementa='Estudo que adapta o TAPP de licitações da ASSGERLICT às dispensas do art. 75, I e II, da Lei nº 14.133/2021. Traz a nota preliminar sobre as fontes (TAPP-modelo nº 15/2026/AGL/CLC, MJR nº 92/2024/CLC/APPL e IN SEGES/ME nº 67/2021) e as entregas 1 (diagnóstico comparativo de cada item do TAPP atual: manter, adaptar ou excluir), 2 (matriz de requisitos da MJR nº 92/2024), 4 (notas de parametrização) e 5 (pontos de atenção para o agente de contratação). A minuta integral do TAPP-D (entrega 3) está em arquivo separado. Revisado pela "Nota Técnica de Revisão da Minuta do TAPP-D".'),
    'POP - Contratacao por ARP Propria (POP-CLC-05, rev. 05.02.2025).pdf': dict(
        tipo='Procedimento Operacional Padrão (POP)', numero='POP-CLC-05', ano=2025, orgao='MPPI / CLC', ambito='MPPI (interno)',
        assunto='Procedimento de contratação por ata de registro de preços do próprio MPPI (serviços com mão de obra residente e não residente, bens de consumo e permanentes), com checklist',
        status='Em uso (revisão nº 02, de 05/02/2025)',
        tags=['pop', 'pop-clc-05', 'ata-de-registro-de-precos', 'srp', 'contratacao-por-arp', 'checklist', 'clc', 'mppi'],
        titulo='POP-CLC-05 — Contratação por Ata de Registro de Preços do MPPI (rev. 05/02/2025)',
        ementa='Manual de procedimento da CLC/MPPI para contratar com base em ata de registro de preços do próprio órgão (inclusive serviços com mão de obra residente e não residente e bens de consumo e permanentes): recursos necessários (DFD, cópia da ARP e extrato de publicação), documentos de referência, equipe, passos críticos por fase e responsável (incluindo o Termo de Aprovação de Artefatos) e checklist de instrução (empenho, contrato ou ordem de fornecimento). Elaborado em 01/03/2023; revisão nº 02 de 05/02/2025.'),
}
