ZEN_ORG = 'Zênite Informação e Consultoria — 2ª Imersão Zênite em Contratação Direta'
ZEN_ST = 'Material de curso comercial (uso restrito; fora do repositório público)'
ZEN_TAGS = ['curso', 'zenite', 'imersao-contratacao-direta', 'contratacao-direta', 'lei-14133']

META = {
    # --- Suprimento de Fundos: normas e manuais ---
    'INSTRUCAO NORMATIVA N_ CCI 001-2011 DIARIAS E ADIANTAMENTOS.doc': dict(
        tipo='Instrução Normativa', numero='CCI 001/2011', ano=2011, orgao='Município de Herval d\'Oeste/SC — Controle Interno', ambito='Municipal (SC)',
        assunto='Adiantamentos e diárias no Poder Executivo municipal: concessão, aplicação e prestação de contas',
        status='Referência comparada (norma municipal de outro ente, anterior à Lei nº 14.133/2021)',
        tags=['instrucao-normativa', 'adiantamento', 'suprimento-de-fundos', 'diarias', 'prestacao-de-contas', 'controle-interno', 'lei-4320', 'municipal', 'sc'],
        titulo='Instrução Normativa CCI nº 001/2011 — Adiantamentos e Diárias (Herval d\'Oeste/SC)',
        ementa='Norma do controle interno do Município de Herval d\'Oeste/SC que disciplina o regime de adiantamentos e o pagamento de diárias, com fundamento na Lei nº 4.320/1964, na Lei nº 8.666/1993, na Lei Complementar municipal nº 281/2011, no Decreto municipal nº 2.821/2010 e na Resolução TC 16/94 do TCE-SC. Referência comparada de regime de adiantamento; texto extraído de arquivo .doc antigo, sem títulos nem listas formatadas.'),
    'Informativo-Suprimento-de-Fundos-Maio-de-2024.pdf': dict(
        tipo='Informativo', numero='', ano=2024, orgao='MPPI — Controladoria Interna', ambito='MPPI (interno)',
        assunto='Orientações da Controladoria Interna sobre cadastro do Cartão de Pagamento, requerimento, condições de uso, vedações, prazos e prestação de contas do suprimento de fundos',
        status='Publicado (maio de 2024)',
        tags=['informativo', 'suprimento-de-fundos', 'cartao-de-pagamento', 'cpmp', 'prestacao-de-contas', 'despesas-de-pequeno-vulto', 'ato-pgj-1228-2022', 'controladoria-interna', 'mppi'],
        titulo='Informativo da Controladoria Interna — Suprimento de Fundos (MPPI, maio de 2024)',
        ementa='Informativo da Controladoria Interna do MPPI que explica, passo a passo, o suprimento de fundos regulamentado pelo Ato PGJ nº 1.228/2022: cadastro prévio na Coordenadoria de Contabilidade e Finanças para emissão do Cartão de Pagamento do Ministério Público (CPMP); requerimento por Procedimento de Gestão Administrativa no SEI, encaminhado à ASSESPPLAGES; hipóteses de uso (despesas em viagem não cobertas por diárias, despesas de pequeno vulto até R$ 479,24, despesas urgentes e inadiáveis e despesas especiais do GAECO), com exemplos e o dever de verificar antes a existência de contratos ou atas vigentes; vedações à concessão; prazo de 90 dias para aplicação; e prestação de contas em até 10 dias, com a lista de documentos exigidos. Texto obtido por OCR.'),
    'CGU - GuiaSuprimento.pdf': dict(
        tipo='Guia', numero='', ano=2024, orgao='Controladoria-Geral da União (CGU)', ambito='Federal',
        assunto='Boas práticas em suprimento de fundos e no uso do Cartão de Pagamento do Governo Federal',
        status='Publicado (junho de 2024; reprodução permitida com citação da fonte)',
        tags=['guia', 'suprimento-de-fundos', 'cartao-de-pagamento', 'cpgf', 'prestacao-de-contas', 'boas-praticas', 'controle-interno', 'cgu', 'federal'],
        titulo='CGU — Guia de Boas Práticas em Suprimento de Fundos e Cartão de Pagamento (2024)',
        ementa='Guia da Controladoria-Geral da União (junho de 2024) com orientações e boas práticas para a concessão, a aplicação e a prestação de contas de suprimento de fundos e para o uso do Cartão de Pagamento do Governo Federal. Referência federal para revisar normas internas de suprimento de fundos e adiantamento.'),
    'MANUAL-DE-ADIANTAMENTO-DO-MP-BA_3a-Edicao_Junho2022.pdf': dict(
        tipo='Manual', numero='3ª edição', ano=2022, orgao='Ministério Público do Estado da Bahia — SGA / DICOFIN', ambito='Estadual (BA) — Ministério Público',
        assunto='Solicitação, aplicação e prestação de contas da verba de adiantamento no MP-BA',
        status='Publicado (3ª edição, junho de 2022)',
        tags=['manual', 'adiantamento', 'suprimento-de-fundos', 'prestacao-de-contas', 'mpba', 'ministerio-publico', 'benchmarking'],
        titulo='MP-BA — Manual de Adiantamento (3ª edição, junho de 2022)',
        ementa='Manual da Diretoria de Contabilidade e Finanças (SGA/DICOFIN) do Ministério Público da Bahia que orienta os usuários da verba de adiantamento sobre a solicitação, a aplicação e a prestação de contas, com base na legislação de finanças públicas e na Instrução Normativa SAF nº 21/2017. Referência de outro Ministério Público para o regime de adiantamento.'),
    'manual_fundo_rotativo_3.pdf': dict(
        tipo='Manual', numero='3ª edição', ano=2023, orgao='Ministério Público do Estado do Paraná — DFI / ACOI / 4ª COE', ambito='Estadual (PR) — Ministério Público',
        assunto='Fundo Rotativo do MPPR: repasses de recursos às unidades, aplicação e prestação de contas',
        status='Publicado (3ª edição, março de 2023)',
        tags=['manual', 'fundo-rotativo', 'suprimento-de-fundos', 'adiantamento', 'prestacao-de-contas', 'mppr', 'ministerio-publico', 'benchmarking'],
        titulo='MPPR — Fundo Rotativo: Manual de Orientações (3ª edição, março de 2023)',
        ementa='Manual de orientações do Ministério Público do Paraná (DFI, ACOI e 4ª Coordenadoria Executiva) sobre o Fundo Rotativo, com fundamento na Lei Estadual nº 17.228/2012 e na Resolução nº 3.875/2012-PGJ: unidades responsáveis, despesas admitidas, procedimentos de aplicação e prestação de contas. Modelo alternativo ao suprimento de fundos tradicional.'),
    'MPES - Portaria-n-7.843-de-22-outubro-de-2015-Suprimentos-de-Fundos.pdf': dict(
        tipo='Portaria', numero='7.843', ano=2015, orgao='Ministério Público do Estado do Espírito Santo — Procuradoria-Geral de Justiça', ambito='Estadual (ES) — Ministério Público',
        assunto='Concessão, aplicação e prestação de contas do suprimento de fundos no MP-ES',
        status='Referência comparada (vigência não verificada)',
        tags=['portaria', 'suprimento-de-fundos', 'adiantamento', 'prestacao-de-contas', 'despesas-sigilosas', 'mpes', 'ministerio-publico', 'benchmarking'],
        titulo='MP-ES — Portaria PGJ nº 7.843/2015 (Suprimento de Fundos)',
        ementa='Portaria do Procurador-Geral de Justiça do Espírito Santo, de 22/10/2015, que regulamenta a concessão, a aplicação e a prestação de contas do suprimento de fundos: limite de até três supridos (Coordenação de Engenharia, Coordenação Administrativa e Assessoria Militar/GAECO), regras para despesas de caráter sigiloso, vedações à concessão, despesas admitidas, prazos e prestação de contas.'),
    'MPMG - 1-1-D646-39-res_pgj_01_2024 _repub.pdf': dict(
        tipo='Resolução', numero='PGJ 1/2024', ano=2024, orgao='Ministério Público do Estado de Minas Gerais — Procuradoria-Geral de Justiça', ambito='Estadual (MG) — Ministério Público',
        assunto='Regime de adiantamento por Cartão de Pagamento para despesas miúdas e de pronto pagamento',
        status='Referência comparada (republicação)',
        tags=['resolucao', 'adiantamento', 'cartao-de-pagamento', 'suprimento-de-fundos', 'despesas-miudas', 'art-95-par-2', 'lei-14133', 'mpmg', 'ministerio-publico', 'benchmarking'],
        titulo='MPMG — Resolução PGJ nº 1/2024 (Regime de Adiantamento, republicação)',
        ementa='Resolução da Procuradoria-Geral de Justiça de Minas Gerais que disciplina o regime de adiantamento operado por Cartão de Pagamento, para despesas miúdas e de pronto pagamento (art. 95, § 2º, da Lei nº 14.133/2021) e outras que não possam seguir o processo normal de despesa. Prevê até quatro adiantamentos por exercício (um por trimestre), limites fixados em anexo e regras de prestação de contas.'),
    'MPRJ - guiarapido_atualizado20_07_21.pdf': dict(
        tipo='Guia', numero='', ano=2021, orgao='Ministério Público do Estado do Rio de Janeiro', ambito='Estadual (RJ) — Ministério Público',
        assunto='Apresentação de contas de curatela: receitas, despesas e documentos comprobatórios',
        status='Publicado (atualizado em 20/07/2021)',
        tags=['guia', 'prestacao-de-contas', 'curatela', 'documentos-comprobatorios', 'mprj', 'ministerio-publico'],
        titulo='MPRJ — Guia Rápido para Apresentação de Contas de Curatela (2021)',
        ementa='Guia rápido do MPRJ para curadores apresentarem a prestação de contas da curatela: como demonstrar receitas e despesas e quais documentos as comprovam. Não trata de suprimento de fundos; veio no mesmo dossiê e serve apenas como referência sobre documentação comprobatória de despesas.'),
    'lei complementar 13.94 - servidores cvis.pdf': dict(
        tipo='Lei Complementar', numero='13', ano=1994, orgao='Estado do Piauí', ambito='Estadual (PI)',
        assunto='Estatuto dos Servidores Públicos Civis do Estado do Piauí, das autarquias e das fundações públicas estaduais',
        status='Em vigor (texto compilado com alterações até a LC nº 84/2007; conferir alterações posteriores)',
        tags=['lei-complementar', 'lc-13-1994', 'estatuto-dos-servidores', 'servidores-publicos', 'diarias', 'regime-disciplinar', 'piaui', 'estadual'],
        titulo='Lei Complementar Estadual nº 13/1994 — Estatuto dos Servidores Públicos Civis do Piauí',
        ementa='Lei Complementar nº 13, de 03/01/1994, que institui o regime jurídico dos servidores públicos civis do Estado do Piauí, das autarquias e das fundações públicas estaduais: provimento, vacância e movimentação; direitos e vantagens, inclusive indenizações como diárias; regime disciplinar e processo administrativo disciplinar. Texto compilado com alterações até a LC nº 84/2007. Referência para diárias, responsabilidade do servidor e regime disciplinar.'),
    '34_suprimento_de_fundos_2ed.pdf': dict(
        tipo='Manual', numero='2ª edição', ano=2016, orgao='Ministério Público Federal (MPF)', ambito='Federal — Ministério Público',
        assunto='Suprimento de fundos e Cartão de Pagamento no MPF: concessão, aplicação e prestação de contas',
        status='Publicado (2ª edição, 2016; todos os direitos reservados, fora do repositório público)',
        tags=['manual', 'suprimento-de-fundos', 'cartao-de-pagamento', 'cpgf', 'prestacao-de-contas', 'mpf', 'ministerio-publico', 'federal'],
        titulo='MPF — Suprimento ou Sofrimento de Fundos? (2ª edição, 2016)',
        ementa='Manual didático do Ministério Público Federal (78 páginas) sobre o suprimento de fundos e o Cartão de Pagamento: concessão, limites, vedações, aplicação dos recursos e prestação de contas. Referência de outro ramo do Ministério Público.'),
    # --- Suprimento de Fundos: custo da licitação e estudos ---
    '32-Custos de uma licitação - NP.pdf': dict(
        tipo='Artigo de Revista', numero='', ano=2015, orgao='Revista Negócios Públicos (Instituto Negócios Públicos)', ambito='Doutrina',
        assunto='Custo médio de uma licitação por fase do processo e alternativas para reduzi-lo',
        status='Publicado (junho de 2015; obra comercial, fora do repositório público)',
        tags=['artigo', 'custo-da-licitacao', 'economicidade', 'planejamento', 'srp', 'compras-compartilhadas', 'negocios-publicos', 'lei-8666'],
        titulo='Custos de uma Licitação — Revista Negócios Públicos (junho de 2015)',
        ementa='Matéria da revista Negócios Públicos (junho de 2015, p. 43) que divulga estudo do Instituto Negócios Públicos (fevereiro de 2015) com o custo de cada fase da licitação e o custo médio total de R$ 14.351,50, superior ao limite de dispensa então vigente. Reúne sugestões para reduzir o custo, como planejamento, Sistema de Registro de Preços e compras compartilhadas.'),
    'Você sabe quanto custa uma licitação_.pdf': dict(
        tipo='Notícia', numero='', ano=2018, orgao='Portal Sollicita', ambito='Doutrina',
        assunto='Custo médio de uma licitação por fase do processo e alternativas para reduzi-lo',
        status='Publicado (10/01/2018; obra comercial, fora do repositório público)',
        tags=['noticia', 'custo-da-licitacao', 'economicidade', 'srp', 'compras-compartilhadas', 'dispensa', 'compras-eletronicas', 'sollicita', 'lei-8666'],
        titulo='Você sabe quanto custa uma licitação? — Portal Sollicita (2018)',
        ementa='Notícia do portal Sollicita (10/01/2018) que retoma o estudo do Instituto Negócios Públicos de 2015: custo de cada fase da licitação e custo médio de R$ 14.351,50, comparado ao limite de dispensa de R$ 8 mil (art. 24, II, da Lei nº 8.666/1993). Traz sugestões de especialistas para reduzir o custo: planejamento, mapeamento de processos, SRP, compras compartilhadas, adesão a atas, publicação eletrônica e atualização dos limites de dispensa. Conteúdo próximo ao do documento "32-Custos de uma licitação - NP".'),
    'QUANTO CUSTA UMA LICITAÇÃO - 2014.pdf': dict(
        tipo='Pesquisa / Estudo', numero='', ano=2014, orgao='Instituto Negócios Públicos do Brasil', ambito='Doutrina',
        assunto='Panorama e custo das contratações públicas no Brasil, em infográficos',
        status='Publicado (edição 2014; reprodução proibida pelo editor, fora do repositório público)',
        tags=['pesquisa', 'infograficos', 'custo-da-licitacao', 'panorama-das-contratacoes', 'negocios-publicos', 'lei-8666'],
        titulo='Instituto Negócios Públicos — Infográficos 2014: Quanto Custa uma Licitação',
        ementa='Publicação do Instituto Negócios Públicos ("Infográficos: Edição 2014") com resultados de pesquisa sobre o panorama das contratações públicas no Brasil e o custo da licitação, apresentados em infográficos. Boa parte das páginas é gráfica e o texto extraído pode vir com colunas misturadas; conferir os números no PDF.'),
    'CONGRESSO CUSTOS 2013.pdf': dict(
        tipo='Artigo Acadêmico', numero='', ano=2013, orgao='Congresso Brasileiro de Custos', ambito='Doutrina',
        assunto='Custeio ABC no setor de compras de uma unidade da UFMG: custo por pedido em dispensa, pregão eletrônico e registro de preços',
        status='Publicado (2013)',
        tags=['artigo', 'custo-da-licitacao', 'custeio-abc', 'dispensa', 'pregao-eletronico', 'srp', 'universidade', 'estudo-de-caso'],
        titulo='Quanto custa comprar? Um estudo de caso na UFMG (Congresso Brasileiro de Custos, 2013)',
        ementa='Estudo de caso que aplica o custeio baseado em atividades (ABC) ao setor de compras de uma unidade da UFMG. O pedido atendido por dispensa custou R$ 372,53, por pregão eletrônico R$ 227,27 e por registro de preços R$ 117,66, o que aponta o registro de preços como a forma mais econômica no caso estudado.'),
    'CONGRESSO CUSTOS 2015.pdf': dict(
        tipo='Artigo Acadêmico', numero='', ano=2015, orgao='Congresso Brasileiro de Custos', ambito='Doutrina',
        assunto='Custo dos processos de compras da Secretaria Municipal de Saúde de Feira de Santana/BA em 2013',
        status='Publicado (2015)',
        tags=['artigo', 'custo-da-licitacao', 'dispensa', 'inexigibilidade', 'tomada-de-precos', 'saude', 'municipal', 'estudo-de-caso'],
        titulo='Custo dos Processos de Compras da Secretaria de Saúde de Feira de Santana/BA (Congresso Brasileiro de Custos, 2015)',
        ementa='Estudo de caso sobre o custo das licitações, dispensas e inexigibilidades realizadas em 2013 pela Secretaria Municipal de Saúde de Feira de Santana/BA. A tomada de preços apresentou o maior custo por processo (R$ 4.912,75).'),
    'CUSTO LICITAÇÃO - CONGRESSO UFSC.pdf': dict(
        tipo='Artigo Acadêmico', numero='', ano=2014, orgao='Universidade Federal de Santa Catarina (UFSC) — autores', ambito='Doutrina',
        assunto='Custo do pregão eletrônico e princípio da economicidade: estudo de caso na Eletrosul',
        status='Publicado (ano provável: 2014; analisa processos do 2º semestre de 2013)',
        tags=['artigo', 'custo-da-licitacao', 'pregao-eletronico', 'economicidade', 'estatal', 'estudo-de-caso'],
        titulo='O Custo do Pregão Eletrônico e o Princípio da Economicidade — Caso Eletrosul',
        ementa='Estudo de caso (Silveira e Ducati, UFSC) que estima os custos variáveis de processamento do pregão eletrônico na Eletrosul a partir de 34 processos do segundo semestre de 2013 e verifica sua razoabilidade diante do princípio da economicidade. Os custos variáveis corresponderam, em média, a 4,19% do valor contratado.'),
    'Carlos Vinicius de Souza Motta.pdf': dict(
        tipo='Trabalho Acadêmico (TCC)', numero='', ano=2020, orgao='Especialização em Gestão Pública — autor: Carlos Vinícius de Souza Motta', ambito='Doutrina',
        assunto='Custos administrativos dos processos de compras da Ebserh',
        status='Publicado (abril de 2020)',
        tags=['tcc', 'custo-da-licitacao', 'custos-administrativos', 'etp', 'termo-de-referencia', 'ebserh', 'estatal', 'saude'],
        titulo='Identificação dos Custos Administrativos dos Processos de Compras da Ebserh (TCC, 2020)',
        ementa='Trabalho de conclusão de especialização em Gestão Pública que estima o custo administrativo dos processos de compras da Ebserh. Os custos variaram de R$ 4.016,19 a R$ 86.449,70 (41 a 533 dias de tramitação), com média de R$ 27.448,31 por processo, e são detalhados por etapa (ETP, termo de referência, minuta de edital, parecer jurídico e demais fases).'),
    'RT 12 - Levantamento de custos - consolidação de todos os órgãos.pdf': dict(
        tipo='Relatório Técnico', numero='RT 12 (versão 2.0)', ano=2007, orgao='PNUD / Governo Federal — Consórcio FIA, IDS-Scheer e Sundfeld Advogados', ambito='Federal',
        assunto='Mapeamento e análise dos custos operacionais dos processos de contratação do Governo Federal, para a Administração e para os fornecedores',
        status='Publicado (maio de 2007)',
        tags=['relatorio-tecnico', 'custo-da-licitacao', 'custo-operacional', 'modalidades-de-licitacao', 'fornecedores', 'federal', 'lei-8666'],
        titulo='RT 12 — Levantamento de Custos: Consolidação de Todos os Órgãos (Custos Operacionais das Contratações do Governo Federal, 2007)',
        ementa='Relatório técnico do contrato PNUD nº 06/47-2825, executado pelo consórcio FIA, IDS-Scheer e Sundfeld Advogados, que consolida o levantamento dos custos operacionais dos processos de contratação em 17 unidades do Governo Federal: metodologia de apuração, custo médio por evento de aquisição em cada órgão (por exemplo, R$ 5.991,21 no FNDE e R$ 30.249,00 no INSS) e custos que o processo licitatório impõe aos fornecedores. Provável fonte do dado FIA/USP sobre o custo de processos de compra citado pela CGU (Nota Técnica nº 1081/2017) e em cursos.'),
    '68_Texto_do_artigo_318_2_10_20200915.pdf': dict(
        tipo='Artigo Acadêmico', numero='', ano=2020, orgao='Revista Cadernos de Finanças Públicas, v. 20, n. 2', ambito='Doutrina',
        assunto='Custos de transação nas licitações de medicamentos de organizações públicas do SUS',
        status='Publicado (setembro de 2020)',
        tags=['artigo', 'custos-de-transacao', 'custo-da-licitacao', 'medicamentos', 'saude', 'sus', 'dispensa', 'eficiencia'],
        titulo='Custos de Transação em Licitações de Medicamentos no SUS (Cadernos de Finanças Públicas, 2020)',
        ementa='Artigo (Ferreira e Souza) que aplica a teoria dos custos de transação às compras de medicamentos por organizações públicas do SUS e propõe um Índice de Custos de Transação. Aponta distorções nas dispensas e nas licitações de lotes pequenos.'),
    'Raquel Pereira Alves.pdf': dict(
        tipo='Projeto de Pesquisa', numero='', ano=2020, orgao='Escola Nacional de Administração Pública (Enap) — autora: Raquel Pereira Alves', ambito='Doutrina',
        assunto='Trilha de aprendizagem sobre o processo de contratação de ações de capacitação no CEFOR/STJ',
        status='Publicado (setembro de 2020)',
        tags=['projeto-de-pesquisa', 'trilha-de-aprendizagem', 'capacitacao', 'contratacao-de-treinamento', 'educacao-corporativa', 'stj', 'enap'],
        titulo='Trilha de Aprendizagem para Contratação de Ações de Capacitação no CEFOR/STJ (Enap, 2020)',
        ementa='Projeto de pesquisa da especialização em Inovação e Tecnologias na Educação da Enap que propõe uma trilha de aprendizagem sobre o processo de contratação de ações de capacitação no Centro de Formação e Gestão Judiciária (CEFOR) do STJ. Útil para capacitação interna em contratações e para a contratação de cursos.'),
    # --- Curso Imersao Zenite (material comercial: .md fica fora do GitHub) ---
    'Programacao.pdf': dict(
        tipo='Programação de Curso', numero='', ano=2026, orgao=ZEN_ORG, ambito='Doutrina', status=ZEN_ST,
        assunto='Programa da 2ª Imersão Zênite em Contratação Direta (Brasília/DF, 5 a 7/08/2026, 24h)',
        tags=ZEN_TAGS + ['programacao', 'dispensa', 'inexigibilidade', 'credenciamento', 'lei-13303'],
        titulo='2ª Imersão Zênite em Contratação Direta — Programação (agosto de 2026)',
        ementa='Programa da 2ª Imersão Zênite em Contratação Direta, realizada em Brasília/DF de 5 a 7 de agosto de 2026 (24h): metodologia (exposições, casos práticos com votação eletrônica, frameworks e "Direto ao Ponto"), público-alvo, programação por turno, professores e valores de inscrição. Trata de dispensa, inexigibilidade e credenciamento nos regimes das Leis nº 14.133/2021 e nº 13.303/2016. Índice útil para localizar os demais materiais do curso.'),
    'Laboratório_Professor_Thiago_Zagatto.pdf': dict(
        tipo='Material de Curso', numero='', ano=2026, orgao=ZEN_ORG, ambito='Doutrina', status=ZEN_ST,
        assunto='Aula prática: simulações no ambiente de treinamento do Compras.gov.br de dispensa eletrônica e de inexigibilidade/credenciamento',
        tags=ZEN_TAGS + ['dispensa-eletronica', 'compras-gov', 'credenciamento', 'inexigibilidade', 'passo-a-passo'],
        titulo='Laboratório — Simulações de Dispensa Eletrônica e Credenciamento no Compras.gov.br (Prof. Thiago Zagatto)',
        ementa='Roteiro ilustrado da aula prática do Prof. Thiago Anderson Zagatto (TCU), com o passo a passo no ambiente de treinamento do Compras.gov.br para três simulações: dispensa eletrônica com disputa (aquisição de café em pó), dispensa eletrônica sem disputa (aquisição de computadores) e inexigibilidade/credenciamento de tradutores. Texto obtido por OCR de capturas de tela; conferir as telas no PDF.'),
    'Informativo Decisões – Nova Lei.pdf': dict(
        tipo='Coletânea de Jurisprudência', numero='', ano=2026, orgao=ZEN_ORG, ambito='Doutrina', status=ZEN_ST,
        assunto='Coletânea de decisões do TCU, de tribunais de contas e do Judiciário sobre a Lei nº 14.133/2021',
        tags=ZEN_TAGS + ['jurisprudencia', 'tcu', 'tribunais-de-contas', 'informativo', 'habilitacao'],
        titulo='Zênite — Informativo de Decisões sobre a Nova Lei de Licitações (Lei nº 14.133/2021)',
        ementa='Coletânea da Zênite (170 páginas), distribuída na 2ª Imersão em Contratação Direta, com resumos de decisões recentes do TCU, de outros tribunais de contas e do Judiciário sobre a Lei nº 14.133/2021, organizadas por tema (por exemplo, habilitação e a declaração de reserva de cargos do art. 63, IV). A maior parte das decisões citadas é de 2023 a 2025; data de edição não identificada. Diagramação em duas colunas: alguns trechos extraídos saem embaralhados.'),
    'Material Selecionado – Produção Zênite – Regime Lei nº 14.133.2021.pdf': dict(
        tipo='Coletânea Doutrinária', numero='', ano=2024, orgao='Zênite Editora', ambito='Doutrina', status=ZEN_ST,
        assunto='Artigos doutrinários e perguntas e respostas da Zênite sobre pontos relevantes da Lei nº 14.133/2021',
        tags=ZEN_TAGS + ['doutrina', 'zenite-facil', 'planejamento', 'inexigibilidade', 'adesao-a-ata', 'regime-de-adiantamento', 'alteracoes-contratuais'],
        titulo='Zênite — Material Selecionado sobre o Regime da Lei nº 14.133/2021 (março de 2024)',
        ementa='Material complementar da Zênite Editora (março de 2024, 154 páginas) com artigos doutrinários e perguntas e respostas da ferramenta Zênite Fácil sobre pontos polêmicos da Lei nº 14.133/2021: princípio do planejamento, publicação em jornal de grande circulação, singularidade na inexigibilidade de serviços técnicos especializados, documento novo na habilitação, presunção de inexequibilidade (art. 59, § 4º), restrição de adesão à ata, regime de adiantamento, alterações contratuais e responsabilidade do gestor na transição de regime, entre outros.'),
    '1.2 - Ponto_de_vista_I_Profa_Michelle_Marry.pdf': dict(
        tipo='Material de Curso', numero='', ano=2026, orgao=ZEN_ORG, ambito='Doutrina', status=ZEN_ST,
        assunto='O papel da assessoria jurídica na análise de legalidade das contratações diretas',
        tags=ZEN_TAGS + ['assessoria-juridica', 'parecer-juridico', 'controle-de-legalidade', 'custo-da-dispensa', 'responsabilizacao'],
        titulo='Ponto de Vista I — O Papel da Assessoria Jurídica nas Contratações Diretas (Profa. Michelle Marry)',
        ementa='Slides da Profa. Michelle Marry Marques da Silva (AGU) sobre o papel da assessoria jurídica no controle de legalidade das contratações diretas, as contratações diretas como zona de maior risco e responsabilização dos agentes, e dados sobre o custo de um processo de dispensa (estudo FIA/USP citado em nota técnica da CGU e relatório da CGU sobre pregões deficitários).'),
    '1.3 - Ponto_de_vista_II_Profa_Suzana_Rossetti.pdf': dict(
        tipo='Material de Curso', numero='', ano=2026, orgao=ZEN_ORG, ambito='Doutrina', status=ZEN_ST,
        assunto='Responsabilidade decisória e instrução processual na contratação direta: governança nas Leis nº 14.133/2021 e nº 13.303/2016',
        tags=ZEN_TAGS + ['instrucao-processual', 'motivacao', 'art-72', 'governanca', 'lei-13303'],
        titulo='Ponto de Vista II — Contratação Direta, Responsabilidade Decisória e a Instrução que Protege (Profa. Suzana Rossetti)',
        ementa='Slides da Profa. Suzana Rossetti (Zênite) sobre o dever reforçado de justificar na contratação direta: a excepcionalidade aumenta o ônus argumentativo, e não apenas o rol de documentos; instrução do processo (art. 72 da Lei nº 14.133/2021) que permita ao controle entender a decisão sem depender da equipe; paralelo com a Lei nº 13.303/2016.'),
    '1.4 - Na_pratica_I.pdf': dict(
        tipo='Material de Curso', numero='', ano=2026, orgao=ZEN_ORG, ambito='Doutrina', status=ZEN_ST,
        assunto='Dispensa por valor: da decisão administrativa à operação eletrônica; fracionamento e unidade gestora',
        tags=ZEN_TAGS + ['dispensa-por-valor', 'art-75', 'fracionamento', 'unidade-gestora', 'dispensa-eletronica', 'in-67-2021'],
        titulo='Na Prática I — Dispensa por Valor: da Decisão Administrativa à Operação Eletrônica (Prof. Thiago Zagatto)',
        ementa='Slides e caso prático do Prof. Thiago Anderson Zagatto (TCU) sobre a dispensa em razão do valor (art. 75, I e II, da Lei nº 14.133/2021): as três análises para evitar o fracionamento indevido (exercício financeiro, ramo de atividade e unidade gestora, conforme a IN Seges/ME nº 67/2021), conceito de unidade gestora, enunciados Zênite e a operação da dispensa eletrônica.'),
    '2.1 - Na_pratica_II.pdf': dict(
        tipo='Material de Curso', numero='', ano=2026, orgao=ZEN_ORG, ambito='Doutrina', status=ZEN_ST,
        assunto='Dispensa emergencial: o que a lei não diz, mas o controle exige; escolha do objeto e legalidade da dispensa',
        tags=ZEN_TAGS + ['dispensa-emergencial', 'art-75-viii', 'emergencia', 'caso-pratico'],
        titulo='Na Prática II — Dispensa Emergencial: o que a Lei não Diz, mas o Controle Exige',
        ementa='Slides e caso prático (enchentes e falha de comunicação entre setores na contratação de barcos pela Defesa Civil) sobre a dispensa emergencial: nem todo contexto emergencial autoriza a contratação direta, a escolha do que contratar diante da emergência e os requisitos que o controle exige além do texto legal.'),
    '2.2 - Na_pratica_III_profa_manuela.pdf': dict(
        tipo='Material de Curso', numero='', ano=2026, orgao=ZEN_ORG, ambito='Doutrina', status=ZEN_ST,
        assunto='Compra e locação de imóvel nas Leis nº 14.133/2021 e nº 13.303/2016: dispensa ou inexigibilidade',
        tags=ZEN_TAGS + ['locacao-de-imovel', 'aquisicao-de-imovel', 'art-74-v', 'art-51', 'inexigibilidade', 'lei-13303'],
        titulo='Na Prática III — Compra e Locação de Imóvel: Dispensa ou Inexigibilidade? (Profa. Manuela Martins de Mello)',
        ementa='Slides e caso prático da Profa. Manuela Martins de Mello (Zênite) sobre a compra e a locação de imóveis: art. 51 e art. 74, V e § 5º, da Lei nº 14.133/2021 (avaliação prévia, certificação de inexistência de imóveis públicos disponíveis e justificativa da singularidade) e o regime da Lei nº 13.303/2016 para as estatais.'),
    '2.3 - Na_pratica_IV.pdf': dict(
        tipo='Material de Curso', numero='', ano=2026, orgao=ZEN_ORG, ambito='Doutrina', status=ZEN_ST,
        assunto='Dispensa interadministrativa (art. 75, IX, da Lei nº 14.133/2021) e seus limites quando a contratada é estatal',
        tags=ZEN_TAGS + ['dispensa-interadministrativa', 'art-75-ix', 'estatais', 'ti', 'lei-13303'],
        titulo='Na Prática IV — Dispensa Interadministrativa e Estatais (Prof. Rodrigo Vissotto Junkes)',
        ementa='Slides e caso prático do Prof. Rodrigo Vissotto Junkes (Zênite) sobre a dispensa do art. 75, IX, da Lei nº 14.133/2021: autarquia universitária estadual que pretende contratar sociedade de economia mista federal para desenvolver software. Analisa a finalidade institucional da contratada, a especialização no objeto, a atuação em mercado e a contratação entre esferas distintas.'),
    '3.3 - Ponto_de_vista_III.pdf': dict(
        tipo='Material de Curso', numero='', ano=2026, orgao=ZEN_ORG, ambito='Doutrina', status=ZEN_ST,
        assunto='Credenciamento: dever ou possibilidade; a inclusão do SICX (Sistema de Compras Expressas) entre as hipóteses de credenciamento',
        tags=ZEN_TAGS + ['credenciamento', 'art-79', 'sicx', 'inexigibilidade', 'jurisprudencia-tcu'],
        titulo='Ponto de Vista III — Credenciamento: Dever ou Possibilidade? (Prof. Ricardo Alexandre Sampaio)',
        ementa='Slides do Prof. Ricardo Alexandre Sampaio (Zênite) sobre o credenciamento: origem e reconhecimento como hipótese de inexigibilidade (TCU, Acórdãos nº 3.567/2014-Plenário e nº 2.504/2017-1ª Câmara), requisitos, se seu uso é dever ou faculdade e a recente inclusão do SICX (Sistema de Compras Expressas) entre as hipóteses de credenciamento na Lei nº 14.133/2021.'),
    # --- Material didatico da CLC ---
    'Estrutura da Apresentação.docx': dict(
        tipo='Material Didático', numero='', ano=2026, orgao='MPPI / CLC', ambito='MPPI (interno)',
        assunto='Estrutura de slides da apresentação sobre o Plano de Contratações Anual (PCA) no MPPI, do analógico ao digital',
        status='Documento de trabalho (2026)',
        tags=['material-didatico', 'apresentacao', 'pca', 'plano-de-contratacoes-anual', 'governanca', 'ato-pgj-1381-2024', 'clc', 'mppi'],
        titulo='Estrutura da Apresentação — PCA no MPPI: do Analógico ao Digital',
        ementa='Roteiro de slides da apresentação da CLC sobre o PCA no MPPI: contexto; base legal (Acórdão TCU 2622/2015, IN 05/2017, Lei nº 14.133/2021 e Atos PGJ nº 1.108/2021 e nº 1.381/2024); fluxo; resultados de 2026 (529 demandas e valor planejado de R$ 50.070.886,53); lições aprendidas; Sistema de Gestão do PCA e próximos passos.'),
    'Roteiro_Video_PCA_MPPI.md': dict(
        tipo='Material Didático', numero='', ano=2026, orgao='MPPI / CLC', ambito='MPPI (interno)',
        assunto='Roteiro de vídeo (cenas, tempos e locução) sobre a apresentação do PCA do MPPI no 3º Encontro Nacional de Gestão Administrativa do MP',
        status='Documento de trabalho (2026)',
        tags=['material-didatico', 'roteiro-de-video', 'pca', 'plano-de-contratacoes-anual', 'cpcia', 'clc', 'mppi'],
        titulo='Roteiro de Vídeo — PCA do MPPI (3º Encontro Nacional de Gestão Administrativa do MP)',
        ementa='Roteiro de vídeo de 3min30s a 4min sobre a apresentação do PCA do MPPI no 3º Encontro Nacional de Gestão Administrativa do Ministério Público (CPCIA 3.0, PGT/Brasília), organizado em cenas com locução sugerida e notas visuais. Par do documento "Estrutura da Apresentação".'),
    'Kahoot_Importacao_AEI.xlsx': dict(
        tipo='Material Didático', numero='', ano=2026, orgao='MPPI / CLC — aula na especialização IFPI × TCE-PI', ambito='Ensino',
        assunto='Planilha de importação no Kahoot de dinâmica gamificada (10 perguntas) sobre o caso fictício AEI',
        status='Documento de trabalho (aula de 26/09/2026)',
        tags=['material-didatico', 'kahoot', 'gamificacao', 'avaliacao', 'estudo-de-caso', 'planejamento-das-contratacoes', 'contratos', 'ifpi', 'tce-pi'],
        titulo='Kahoot — Dinâmica Gamificada do Caso AEI (Disciplina 13, 26/09/2026)',
        ementa='Planilha para importar no Kahoot as dez perguntas de múltipla escolha (formato Quiz) da dinâmica avaliativa da Disciplina 13 da especialização IFPI × TCE-PI, em 26/09/2026, baseadas no caso fictício AEI, com a regra de nota de 0 a 10.'),
    'Roteiro_Executivo_Chefia.docx': dict(
        tipo='Material Didático', numero='', ano=2026, orgao='MPPI / CLC — Assessoria de Compras', ambito='MPPI (interno) / Ensino',
        assunto='Roteiro executivo, para validação da chefia, da aula "Contratos e Planejamento das Contratações Públicas" na especialização IFPI × TCE-PI',
        status='Documento de trabalho (aula de 26/09/2026)',
        tags=['material-didatico', 'roteiro', 'aula', 'planejamento-das-contratacoes', 'pca', 'contratos', 'art-169', 'ifpi', 'tce-pi'],
        titulo='Roteiro Executivo — Aula "Contratos e Planejamento das Contratações Públicas" (IFPI × TCE-PI, 26/09/2026)',
        ementa='Roteiro submetido à validação da chefia para a aula da Disciplina 13 (Turma 01, NPPG/IFPI, convênio com o TCE-PI) em 26/09/2026, com 5 horas: Parte I, planejamento das contratações e PCA, com o caso do MPPI; Parte II, contratos administrativos; Parte III, controle e linhas de defesa (art. 169 da Lei nº 14.133/2021); avaliação por Kahoot.'),
    'Roteiros_Fala_Escrita_Curso_Interno_MPPI.docx': dict(
        tipo='Material Didático', numero='', ano=2026, orgao='MPPI / CLC', ambito='MPPI (interno)',
        assunto='Roteiros de fala (vídeo) e de escrita (lição) do curso interno "Contratação Direta na Prática: Dispensa e Inexigibilidade" no AVA MPPI',
        status='Documento de trabalho (2026)',
        tags=['material-didatico', 'curso-interno', 'ava-mppi', 'contratacao-direta', 'dispensa', 'inexigibilidade', 'zenite', 'capacitacao', 'clc', 'mppi'],
        titulo='Roteiros de Fala e Escrita — Curso "Contratação Direta na Prática: Dispensa e Inexigibilidade" (AVA MPPI)',
        ementa='Roteiros do curso interno da CLC no AVA MPPI (8 tópicos, 6 blocos temáticos): para cada tópico, uma versão para narração em vídeo e outra para a página da lição. Conteúdo baseado nos materiais da 2ª Imersão Zênite em Contratação Direta (5 a 7/08/2026, 24h), sobre dispensa e inexigibilidade na Lei nº 14.133/2021.'),
    'Roteiro_Resumido_1pagina.pdf': dict(
        tipo='Material Didático', numero='', ano=2026, orgao='MPPI / CLC — Assessoria de Compras', ambito='Ensino',
        assunto='Roteiro resumido de uma página da aula "Planejamento das Contratações Públicas" para a turma de servidores do TCE-PI',
        status='Documento de trabalho (aula de 26/09/2026)',
        tags=['material-didatico', 'roteiro', 'aula', 'planejamento-das-contratacoes', 'pca', 'dfd', 'etp', 'gestao-de-riscos', 'tce-pi'],
        titulo='Roteiro Resumido — Planejamento das Contratações Públicas (pós-graduação, TCE-PI, 26/09/2026)',
        ementa='Roteiro de uma página da aula de 2 horas (1h30 de apresentação e 30 min de debate) para a turma de servidores e comissionados do TCE-PI na pós-graduação, em 26/09/2026: abertura, tese central (a prevenção como melhor estratégia e o princípio da boa administração), PCA (art. 12, VII, e art. 11, parágrafo único, da Lei nº 14.133/2021, com o caso do MPPI), DFD, ETP e riscos, erros comuns, controle e encerramento.'),
    # --- Modelos ---
    'Modelo - Manifestacao do Ordenador de Despesas - Liberacao de Adesao a ARP (Acordao TCE-PI 394-A-2026).docx': dict(
        tipo='Modelo', numero='', ano=2026, orgao='MPPI / CLC', ambito='MPPI (interno)',
        assunto='Manifestação do Ordenador de Despesas que toma ciência dos Acórdãos TCE-PI nº 394 e 394-A/2026 e autoriza, com fundamentação, a liberação de adesões à ARP',
        status='Modelo (2026)',
        tags=['modelo', 'manifestacao', 'ordenador-de-despesas', 'arp', 'adesao', 'prorrogacao-de-arp', 'saldo-remanescente', 'art-84', 'art-86', 'acordao-tce-pi-394-2026', 'tce-pi', 'mppi'],
        titulo='Modelo — Manifestação do Ordenador de Despesas: Liberação de Adesão a ARP (Acórdão TCE-PI 394-A/2026)',
        ementa='Modelo de manifestação (relatório, fundamentação e dispositivo) em que o Ordenador de Despesas toma ciência dos Acórdãos nº 394/2026 e nº 394-A/2026-PLENO do TCE-PI (consulta TC/007773/2026, Rel. Cons. Abelardo Pio Vilanova e Silva, DOE TCE-PI nº 156 de 24/08/2026) sobre os arts. 84 e 86 da Lei nº 14.133/2021 e o saldo remanescente na prorrogação da ARP, e autoriza, com fundamentação, a liberação de adesões. Dados do caso concreto substituídos por marcadores.'),
    'Modelo - Oficio ao Orgao Aderente - Efetivacao da Contratacao por Adesao a ARP.docx': dict(
        tipo='Modelo', numero='', ano=2026, orgao='MPPI / CLC', ambito='MPPI (interno)',
        assunto='Ofício ao órgão aderente pedindo informações sobre a efetivação da contratação decorrente de adesão autorizada à ARP',
        status='Modelo (2026)',
        tags=['modelo', 'oficio', 'arp', 'adesao', 'orgao-gerenciador', 'controle-de-adesoes', 'art-86', 'mppi'],
        titulo='Modelo — Ofício ao Órgão Aderente: Efetivação da Contratação por Adesão a ARP',
        ementa='Modelo de ofício da CLC, como órgão gerenciador, ao órgão aderente, pedindo informações sobre a efetivação da contratação decorrente da adesão autorizada à ARP, para controle do saldo da ata. Dados do caso concreto substituídos por marcadores.'),
}
