META = {
    'Ato PGJ 1106.2021 - Novo Fluxo da Controladoria Interna.pdf': dict(
        tipo='Ato', numero='1106', ano=2021, orgao='PGJ/MPPI', ambito='MPPI',
        assunto='Novo fluxo de trabalho da Controladoria Interna: parecer ao final do procedimento de despesa, com exceções (altera o art. 59, XI, do Ato PGJ 479/2014)',
        status='Vigente com alterações (alterado pelo Ato PGJ 1480/2025)',
        tags=['mppi', 'ato-pgj', 'controladoria-interna', 'controle-interno', 'parecer', 'execucao-da-despesa', 'ato-pgj-479-2014', 'ato-pgj-1480-2025'],
        titulo='Ato PGJ nº 1.106/2021 — Novo fluxo de trabalho da Controladoria Interna',
        ementa='Altera o Ato PGJ nº 479/2014 para instituir novo fluxo de trabalho junto à Controladoria Interna. O art. 1º dá nova redação ao art. 59, XI: a Controladoria emite parecer ao final do procedimento, imediatamente antes da decisão do gestor, em todos os processos de execução de despesa, exceto os listados nas alíneas a a j (entre eles despesas correntes, tributos, aluguéis, aditivos sem alteração de valor, contratações por dispensa ou inexigibilidade até os limites do art. 24, I e II, da Lei nº 8.666/1993 e contratações pelo Sistema de Registro de Preços da instituição). O art. 2º acrescenta o § 3º: a pedido de qualquer unidade interessada ou do ordenador de despesas, a Controladoria pode analisar a legalidade e a legitimidade de um processo de despesa antes do pagamento. Atenção: o Ato PGJ nº 1.480/2025 deu nova redação às alíneas h e k desse inciso, já pela Lei nº 14.133/2021, e acrescentou os §§ 4º e 5º ao art. 59 (análise dos procedimentos licitatórios, ordinariamente, antes da homologação). Para a regra em vigor, leia também `01_Normativos_Vigentes/03_MPPI/Atos/Ato PGJ 1480.2025 - Retira CONINT da Fase Interna.md`.'),
    'Ato PGJ 1480.2025 - Retira CONINT da Fase Interna.pdf': dict(
        tipo='Ato', numero='1480', ano=2025, orgao='PGJ/MPPI', ambito='MPPI',
        assunto='Controladoria Interna: análise dos procedimentos licitatórios antes da homologação, exceções para dispensa e inexigibilidade de pequeno valor e listas de verificação no SINCIN (altera o art. 59 do Ato PGJ 479/2014)',
        status='Vigente',
        tags=['mppi', 'ato-pgj', 'controladoria-interna', 'controle-interno', 'tres-linhas-de-defesa', 'gestao-de-riscos', 'listas-de-verificacao', 'sincin', 'homologacao', 'ato-pgj-479-2014', 'ato-pgj-1106-2021', 'lei-14133'],
        titulo='Ato PGJ nº 1.480/2025 — Controladoria Interna antes da homologação e listas de verificação',
        ementa='Altera o art. 59 do Ato PGJ nº 479/2014 e acrescenta às atribuições da Controladoria Interna a elaboração de listas de verificação para a conformidade dos procedimentos de gestão administrativa, com base no modelo das três linhas de defesa (art. 169 da Lei nº 14.133/2021). O art. 1º dá nova redação às alíneas h e k do inciso XI, que ficam fora do parecer da Controladoria: dispensas com base no art. 75, I e II, e inexigibilidades (art. 74) cujo valor não ultrapasse esses limites, conforme a natureza. Acrescenta os §§ 4º e 5º: a análise dos procedimentos licitatórios pela Controladoria passa a ser feita, ordinariamente, antes da homologação pela autoridade competente, ressalvadas as alíneas h e k; isso não impede a análise de um procedimento ou contratação, em qualquer fase, quando pedida pela autoridade competente para a homologação, pelo ordenador de despesa, pelo fiscal do contrato ou por qualquer unidade administrativa. O art. 2º manda a Controladoria elaborar listas de verificação, a serem usadas por ela e pelas demais unidades no SINCIN (Sistema Integrado de Controle Interno). A redação anterior do art. 59, XI, é a do Ato PGJ nº 1.106/2021 (`01_Normativos_Vigentes/03_MPPI/Atos/Ato PGJ 1106.2021 - Novo Fluxo da Controladoria Interna.md`).'),
}
